### ISSUE TITLE
Quest issue for MVP

### ISSUE THREAD

**Issue by samselikoff** [ember-learn/ember-cli-addon-docs#1]
Prioritized features for MVP:

- [ ] Versioned API docs
- [ ] Versioned guides
- [ ] Boilerplates for using these

**Comment by samselikoff** [comment]
Discuss

**Comment by samselikoff** [comment]
I actually think auto-versioned API docs from YUI comments, and some sane structure/process for versioned guides are the only two features to ship an MVP. If we had a good solution for both of these, there's basically no reason any addon shouldn't install this.

**Comment by dfreeman** [comment]
> I actually think auto-versioned API docs from YUI comments, and some sane structure/process for versioned guides are the only two features to ship an MVP.

I'd agree that those two things would constitute a solid MVP here.

Can you elaborate on how you imagine the versioned guides working? Would each version be a separate dummy app, or do you imagine them coexisting within a single application? Separate apps seem like they may be thorny to maintain and deploy, but if the guides include live (and possibly editable) examples, having multiple versions coexist in a single application could be difficult.

**Comment by samselikoff** [comment]
Let's discuss in https://github.com/ember-learn/ember-cli-addon-docs/issues/2
