### ISSUE TITLE
Make the `docs-viewer` sidebar mobile-friendly

### ISSUE THREAD

**Issue by alexlafroscia** [ember-learn/ember-cli-addon-docs#100]
I think the `docs-viewer` sidebar should collapse to the side on mobile. I'd love to implement this if there's interest in making it happen! Thoughts?

**Comment by pzuraq** [comment]
@samselikoff is currently working on a pretty big redesign, we should see where he's at on this

**Comment by samselikoff** [comment]
Yes after EmberConf I will tidy up the design and make it mobile 👍

**Comment by alexlafroscia** [comment]
Sweet! I'll hold off on giving this a shot, then

**Comment by samselikoff** [comment]
Follow https://github.com/ember-learn/ember-cli-addon-docs/issues/109 for progress
