### ISSUE TITLE
Allow addon to work with `yarn link`

### ISSUE THREAD

**Issue by alexlafroscia** [ember-learn/ember-cli-addon-docs#108]
Right now, you can't `yarn link` the `ember-cli-addon-docs` to run a locally-cloned version against your own addon (which I want to do while fixing #94). The error I'm getting now is:

```
runtime.js:3096 Uncaught TypeError: Cannot read property 'concat' of undefined
    at WrappedBuilder.compile (runtime.js:3096)
    at ComponentLayoutBuilder.compile (runtime.js:2989)
    at compileLayout (runtime.js:2970)
    at Cache.func (environment.js:78)
    at Cache.get (ember-metal.js:2678)
    at Environment.getCompiledBlock (environment.js:154)
    at OutletComponentManager.layoutFor (outlet.js:55)
    at runtime.js:1716
    at AppendOpcodes.evaluate (runtime.js:70)
    at VM.next (runtime.js:7246)
```

From somewhere in the Glimmer runtime. I've been trying to figure out exactly which file it corresponds to, but am having a bit of trouble working that out

**Comment by alexlafroscia** [comment]
I realized my addon is using a pretty old version of `@glimmer/runtime` and that might be the cause. I'll update my addon's Ember version and see if that's the cause. It explains why I was having trouble hunting down the location of the problem in the Glimmer source, too

**Comment by dfreeman** [comment]
I would guess that your diagnosis is right -- that stack trace looks similar to things I've seen with mismatched versions of the template compiler vs the runtime. It's likely something we could be more intelligent about, but in general I've had success linking addon docs while developing it against other addons.

**Comment by alexlafroscia** [comment]
Cool. It took a bit of effort to get my addon up-to-date with Ember 3's conventions, but that's finally done. I'll check this out again and make sure that I'm still not getting an error.

Originally there was an additional issue around decorators, but that was solved already.

**Comment by alexlafroscia** [comment]
Confirmed that it was the mis-match with the Glimmer dependencies. Works just fine with my addon upgraded to Ember 3.
