### ISSUE TITLE
New error: @babel/template placeholder "ADDON_DOCS_DEPLOY_VERSION": Expected string substitution

### ISSUE THREAD

**Issue by csprocket777** [ember-learn/ember-cli-addon-docs#1132]
Since yesterday, the my builds have been failing because of a specific error:

`/[...projectFolderPath...]/@embroider/macros/runtime.js: @babel/template placeholder "ADDON_DOCS_DEPLOY_VERSION": Expected string substitution`

I'm using `ember-cli-addon-docs@4.2.2`.

How do I resolve this? How do I troubleshoot this?

**Comment by SergeAstapov** [comment]
@csprocket777 could you please check if you experience the issue described in https://github.com/FortAwesome/ember-fontawesome/issues/194 and https://github.com/embroider-build/embroider/issues/1077 by checking in your lock file if any `@embroider/macros` < 1.0.0 present in your tree?

**Comment by csprocket777** [comment]
Is the solution to pin `@embroider/macros` in my resolutions like in this comment:
