### ISSUE TITLE
Github links not not working after deployment to gh-pages

### ISSUE THREAD

**Issue by bravo-kernel** [ember-learn/ember-cli-addon-docs#123]
Unsure what is happening here but all links pointing to Github appear broken on my gh-pages deployed site (https://alt3.github.io/ember-light-table-cell-type-link/latest/).

Link in my navbar:

```html
https://alt3.github.io/ember-light-table-cell-type-link/latest/[object%20Object]
```

"Edit this page" link:

```html
https://alt3.github.io/ember-light-table-cell-type-link/latest/[object%20Object]/edit/master/tests/dummy/app/undefined
```

**Comment by alexlafroscia** [comment]
Is your `repository` field in `package.json` an object? This happened to me when I had it configured that way. Replacing it with just a `string` of the Github URL fixed this problem.

**Comment by dfreeman** [comment]
Currently we're pulling the entire contents of `package.json` into the build, and as far as I know we're doing that just to get the project name, version and repo location.

We're already using `hosted-git-info` to parse the `repository` field elsewhere—I'd love to stop [passing `packageJson` around](https://github.com/ember-learn/ember-cli-addon-docs/search?utf8=%E2%9C%93&q=packagejson&type=) and just pull out the bits we need, including proper handling for determining the repo URL.

**Comment by alexlafroscia** [comment]
If you check out these repos, you can see how I have it configured, where it sort of generates the right URLs for GitHub.

http://alexlafroscia.com/ember-steps/master/docs/
http://alexlafroscia.com/ember-cli-react/master/docs/

https://github.com/alexlafroscia/ember-steps/blob/851425f9e4be24ee2d587fd2fecf49c86f05ccb3/package.json#L16

It doesn't quite use the shorthand syntax, it's the "full" Github URL

The only problem is that the `Edit this page` URLs aren't actually correct in the UI of the site. For example, trying to edit the "homepage" for the `ember-steps` documentation takes me here:

```
https://github.com/alexlafroscia/ember-steps/edit/master/tests/dummy/app/undefined
```

**Comment by bravo-kernel** [comment]
@dfreeman much appreciated 👏

**Comment by allthesignals** [comment]
Hmm I am also now seeing this same issue. "Edit this page" is pointing to an undefined broken link: https://github.com/NYCPlanning/ember-mapbox-composer/edit/master/tests/dummy/app/undefined. 

Here's my `repository` field: "repository": "https://github.com/NYCPlanning/ember-mapbox-composer". Do I need to add something to `config/environment`? It seems to not be able to pick up anything.
