### ISSUE TITLE
Indent `subnav` in docs viewer

### ISSUE THREAD

**Issue by alexlafroscia** [ember-learn/ember-cli-addon-docs#126]
Updating to version 3 removed the indentation that the `subnav` within the docs viewer had. I liked this visual distinction.

Originally it was like this:

<img width="249" alt="screen shot 2018-03-26 at 4 34 45 pm" src="https://user-images.githubusercontent.com/1645881/37938611-9fd32b92-3113-11e8-90b9-132df049d60f.png">

But now it's all flattened

<img width="205" alt="screen shot 2018-03-26 at 4 35 12 pm" src="https://user-images.githubusercontent.com/1645881/37938620-ae1ab864-3113-11e8-96df-09669d1eeae9.png">

Would you be interested in a PR that fixed this?

If there is reason to avoid indenting it, I think you should just remove that component entirely since I'm pretty sure it doesn't do anything differently than just defining all of the links outside of the `subnav`.

**Comment by pzuraq** [comment]
I Definitely think we should bring this back, definitely interested in a PR. 

We could keep the first level flattened to go with the new aesthetic @samselikoff introduced, I think the differences in font weight, color, and casing should be enough visually distinguish the two and in the minimal case looks very nice. For nested menus and API docs especially though I think it makes sense.

**Comment by alexlafroscia** [comment]
Sweet. I'll look into doing this!

**Comment by alexlafroscia** [comment]
I kind of like the idea of sub-nav being "collapsible" like that, too.

Making `Tabbed` and `Wizard` a "heading" is a fine approach, too. My desire was to have a root, "basic usage" page for each, with additional, more complex examples nested under it. But I can also just add a "basic usage" page explicitly as well.

**Comment by pzuraq** [comment]
So we added the indenting feature of the subnav back so you should be able to use it like before. Do we still want to pursue a collapsible nav you think? I could see it being useful, definitely open to it.

**Comment by samselikoff** [comment]
I think if we want to support like a tertiary nav, we should add collapsible. But we can hold off.

Also if we move API to its own top-level page then we buy ourselves a level of nav.

**Comment by samselikoff** [comment]
The new design has sub-items flattened again, and we'll definitely add collapsibility at some point in the future
