### ISSUE TITLE
Decorator is not a function error

### ISSUE THREAD

**Issue by derrabauke** [ember-learn/ember-cli-addon-docs#1309]
Hi folks,

Building works fine, but as soon as I want to visit the docs page I get the following error:
![image](https://user-images.githubusercontent.com/10029904/182791686-b07a768f-db59-48e6-8b1e-f3f119fdcb5f.png)

Current setup:
```json
"ember-cli": "3.28.5",
"ember-data": "3.28.10",
"ember-cli-addon-docs": "5.0.0",
"highlight.js": "11.6.0"
```

After downgrading to the following deps it works fine again:
```json
"ember-cli-addon-docs": "4.2.2",
"highlight.js": "10.7.2"
```
The error hint to `tracked-toolbox` didn't :bulb: me so far. Tried to update my "tracked-toolbox" dep to "^2.0.0" and also with the old "^1.2.3" setup - still the same error.

Do you guys have any clue what went wrong?

**Comment by derrabauke** [comment]
I could fix it in our monorepo with the following resolution:
```json
  "resolutions": {
    "**/tracked-toolbox": "^1.2.3"
  },
```
Tried updating to `"tracked-toolbox": "^2.0.0"` in all sub-packages as well (without the resolution ofc), but it would not fix the issue. So I reset them to `^1.2.3` and put the resolution in place.

**Comment by RobbieTheWagner** [comment]
We have a dependency on tracked-toolbox v2, so I would expect you need to have everything on 2.x for it to work.

**Comment by derrabauke** [comment]
Works now with `tracked-toolbox: ^2.0.0` and `ember-cli-addon-docs: ^6.0.2`. Thx
