### ISSUE TITLE
Drop Node v4 support

### ISSUE THREAD

**Issue by bravo-kernel** [ember-learn/ember-cli-addon-docs#131]
It seems adding tailwind has bumped the required node version to 6.9.0 or higher whereas the previous builds ran ran perfectly against node 4, using the Ember recommended addon settings :

    # we recommend testing addons with the same minimum supported node version as Ember CLI
    # so that your addon works for all apps
    - "4"

Error from Travis:

```
error tailwindcss@0.4.3: The engine "node" is incompatible with this module. Expected version ">=6.9.0"
```

Build details at https://travis-ci.org/alt3/ember-light-table-cell-type-link/jobs/359024220

**Comment by dfreeman** [comment]
It looks like `punycode` (via `ember-cli-tailwind`'s `jsdom` dep) introduces an incompatibility as well. Node 4 is [EOL as of April 30](https://github.com/nodejs/Release#release-schedule), and I know `ember-cli-addon-docs-esdoc` already has its minimum set at 6, but so far we'd managed to avoid that in the core.

@samselikoff @pzuraq Thoughts? It seems like our options are likely:
 - Go ahead and jump ship on node 4, and by extension maybe be a catalyst for other addons starting to do so ahead of schedule and in contradiction to the official recommendations of the CLI team
 - Hold off on Tailwind (😢) or try to see about lowering the engine requirement there ([that change itself](https://github.com/tailwindcss/tailwindcss/pull/40) doesn't seem to have been tied to wanting a particular language feature in Node 6, but it may also be a hard argument to make for a version that's dying in a month anyway)

**Comment by samselikoff** [comment]
Ya prob not worth it for a version dying in a month.

We could enable `ember-cli-tailwind` during dev then shut it off, and copy+paste the generated `tailwind.css` file and just `app.import` it? Eventually I want to use the dev-time build functionality of ember-cli-tailwind to pare down our styles + colors, but for now we can just ship a static build.

**Comment by dfreeman** [comment]
Even that might be more trouble than it's worth, unless you're just itching to make that change 🙂 

Maybe we're just the Problem Child for the next 33 days and then we let the issue solve itself?

**Comment by bravo-kernel** [comment]
As an end-user I had no idea Node was this close to EOL but looking at https://github.com/nodejs/Release IMHO **putting any effort into version 4 makes no sense to me**.

I do think this repo should clearly state/promote that we follow the Ember support cycle. Maybe we can add a `Requirements` note to the `Usage` page stating something similar to:

```
Addon Docs follows the support cycle of Ember and support. For supported versions see...
```

Please let me know if this is welcomed, otherwise feel free to close this ticket.

**Comment by pzuraq** [comment]
I'm inclined to agree here, Node v4 is going to be dropped very, very soon and this package isn't even technically v1.0.0 yet. I think setting the bar at v6 is reasonable, if anything it'll encourage people to upgrade sooner, which should help get as many addons updated as soon as possible
