### ISSUE TITLE
Github link in the header says [Object object]

### ISSUE THREAD

**Issue by raido** [ember-learn/ember-cli-addon-docs#134]
If package.json includes "repository: { type, url }" object, then link in the header fails to render correctly.

This https://github.com/ember-learn/ember-cli-addon-docs/blob/master/addon/components/docs-header/template.hbs#L30 assumes plain string from package.json.

**Comment by bravo-kernel** [comment]
Dupe of https://github.com/ember-learn/ember-cli-addon-docs/issues/123
