### ISSUE TITLE
Question: ember-code-snippet dependency

### ISSUE THREAD

**Issue by ATurn312** [ember-learn/ember-cli-addon-docs#135]
RE:   "ember-code-snippet": "ef4/ember-code-snippet"

Embarrassed to ask this, but will this dependency eventually point to an npm package version?  Our corporate firewall/proxy blocks pulling packages directly from github projects...

**Comment by dfreeman** [comment]
Hi @ATurn312! Totally reasonable question — we're relying on a commit that's currently only on `master` from that repo right now, but I bet if we ask @ef4 nicely he'd cut a release for us 🙂

**Comment by samselikoff** [comment]
335c0c2237d56eb1412ca7a49949cf78cea8b831 closes
