### ISSUE TITLE
Private members can be displayed multiple times in generated API page

### ISSUE THREAD

**Issue by andrewpye** [ember-learn/ember-cli-addon-docs#138]
Checking and unchecking the `private` checkbox in the API page for a component causes extra copies of the component's private members to be rendered:

![private-members-multiple-copies](https://user-images.githubusercontent.com/5737342/38356230-de96a938-38c7-11e8-88b4-8d1a47a74c60.gif)

If it's of any use, this is the source of the component in the GIF:

```js
// my-component.js
import Component from '@ember/component';

/**
 * Some new component I made.
 *
 * @class my-component
 * @public
 */
export default Component.extend({
  /**
   * Some public field
   *
   * @property publicField
   * @type {String}
   * @default null
   * @public
   */
  publicField: null,

  /**
   * Some private field
   *
   * @property privateField
   * @type {String}
   * @default null
   * @private
   */
  privateField: null,
});
```

**Comment by pzuraq** [comment]
That is definitely a bug, thanks for the report! I'll take a look tomorrow, likely something wrong with the filtering logic
