### ISSUE TITLE
`<DocsHeader::SearchBox />` component throws error with newer version of `ember-data`

### ISSUE THREAD

**Issue by barryofguilder** [ember-learn/ember-cli-addon-docs#1390]
I created a V2 addon and am using a full Ember app for my docs. The Ember app is using `ember-data` 4.9.1. When I install `ember-cli-addon-docs`, I get an error when running the docs app. **I do want to mention that if I create a V1 addon, the same outcome happens, so it doesn't seem to be tied to V2 at all.**

<img width="686" alt="Screenshot 2023-02-25 at 12 08 42 PM" src="https://user-images.githubusercontent.com/5649106/221374138-550276d0-79f6-4422-86f6-c1523a3be5e9.png">

If I downgrade `ember-data` to 4.7.3, the error goes away. I've narrowed it down to when the constructor calls the `fetchProject` task in the `<DocsHeader::SearchBox />` component ([here](https://github.com/ember-learn/ember-cli-addon-docs/blob/39adaead474ac5526535230a8dbd4918e6f21691/addon/components/docs-header/search-box/index.js#L14)). If I add a try/catch around the call, it will throw an error and get swallowed, and the app works. I'm not sure why it's throwing an error.

<img width="577" alt="Screenshot 2023-02-25 at 1 42 58 PM" src="https://user-images.githubusercontent.com/5649106/221374231-fea159d8-4485-47d6-a202-02fd900fa8d6.png">

Here's a [bare bones GitHub repository](https://github.com/barryofguilder/addon-docs-issue-with-v2) reproducing the issue. I've added all the steps in the README file for what I did and which versions of `ember-data` don't work.

**Comment by NullVoxPopuli** [comment]
I bet this is another case of tracked data changing during render.
in `fetchProject`, if you add `yield Promise.resolve()` above the findRecord, is the error resolved?

**Comment by barryofguilder** [comment]
> I bet this is another case of tracked data changing during render. in `fetchProject`, if you add `yield Promise.resolve()` above the findRecord, is the error resolved?

When I do that, the page renders, but the error is still thrown. And once that error is thrown, the app stops working.

**Comment by SergeAstapov** [comment]
@barryofguilder this looks like the same issue as https://github.com/emberjs/data/pull/8439, could you please confirm if this still happens with latest ember-data?

**Comment by SergeAstapov** [comment]
@barryofguilder going to close as the root cause of the issue was fixed. feel free to reopen if issue persists.
