### ISSUE TITLE
Not GDPR compliant out of the box

### ISSUE THREAD

**Issue by mixonic** [ember-learn/ember-cli-addon-docs#1415]
Addon docs uses Google fonts via https://github.com/ember-learn/ember-cli-addon-docs/blob/b330f9af6e159655aba360bee48f646dd382ad7a/index.js#L227

As Google may use their fonts service to analyze user behavior (at the least gathering IP addresses), and there is no clear way for a user to opt-out, addon docs websites may not be GDPR compliant out of the box.

This could be resolved by having the site serve the font asset, not using a custom font at all, or by finding a GDPR compliant font hosting service.

At the least, a documented workaround should be available.

**Comment by mixonic** [comment]
@SergeAstapov @RobbieTheWagner @miguelcobain I'm happy to solve this any of a few ways if you can give me a rough approval for what you think reasonable. Options available seem like:

1. Add a build-time configuration that allows users to disable the font link. Add this to the docs. (requires a minor release)
2. Change the default fonts to be appropriate system serif/sans fonts, and describe in the docs how to set a custom font. (would be a major release)
3. Download and check the font into the assets of the theme so they come from the same domain instead of Google. (requires a minor release)

**Comment by RobbieTheWagner** [comment]
@mixonic addon docs is mostly unmaintained now, since it won't work with v2 addons, embroider, or fastboot. If anyone wants to put in some time to help with those things, I would love to keep it going, but as of right now, there isn't really a path forward.

**Comment by mixonic** [comment]
@RobbieTheWagner I'll keep that in mind, but I'd still love to address this issue upstream instead of forking for it. I'll take it your vote as "do the least effort thing unless you are fixing one of these other three issues as well".

**Comment by RobbieTheWagner** [comment]
Yeah, that's an accurate assessment. I'm fine with any fix.
