### ISSUE TITLE
Issues recompiling, possibly typescript related

### ISSUE THREAD

**Issue by machty** [ember-learn/ember-cli-addon-docs#144]
I tried e-cli-addon-docs but found that my ember serve stalled on the first attempt to recompile the app after changing a markdown file (or any file really), and it only started happening after adding e-cli-addon-docs.

Here's what I see

![image](https://user-images.githubusercontent.com/81818/38496867-0db8a2d6-3bcd-11e8-9101-048b33250957.png)

It never successfully recompiles after this point, attempting to reload the browser just spins indefinitely.

Here's the branch of ember-constraint-router that demonstrated this. To reproduce, run `ember s`, let it compile once, then change one of the `.md` files in the tests/dummy/app folder.

**Comment by machty** [comment]
This is a TypeScript-related issue that is fixed by this [ember-cli-typescript PR](https://github.com/typed-ember/ember-cli-typescript/pull/172)

**Comment by brianhjelle** [comment]
I am having the same issue but I am not using ember-cli-typescript in my addon.  Is ember-cli-addon-docs using ember-cli-typescript? I'm on version 0.6.0 of ember-cli-addon-docs.
