### ISSUE TITLE
Error: File not found: addon.sass

### ISSUE THREAD

**Issue by czikarito** [ember-learn/ember-cli-addon-docs#146]
I am trying to use `ember-cli-addon-docs` in my addon but during building, broccoli throws error related to addon.sass. 
Error:
![image](https://user-images.githubusercontent.com/15904756/38561821-5b769764-3cd9-11e8-909b-118fe70fc6a8.png)

My  project supports `*.sass` (based on `ember-cli-sass` setting) but `ember-cli-addon-docs` has addon.scss

This issue is probably connected with https://github.com/aexmachina/ember-cli-sass/issues/163

I made a repo which contains the minimal setup to reproduce this issue.
https://github.com/czikarito/ember-cli-addon-docs-fix

`ember-freestyle` has the same issue -->https://github.com/chrislopresto/ember-freestyle/issues/143

**Comment by lamabiker** [comment]
Does moving the styles to `app/styles/` in your addon and changing `addon.sass` to `<your-addon-name>.sass` not solve that issue?

If it's the dummy app that's not compiling, a fix could be to create an `app.scss` alongside an `app.sass` and include the `app.sass` in the `app.scss`
