### ISSUE TITLE
Figure out how to put global styles on body or wrapper div

### ISSUE THREAD

**Issue by samselikoff** [ember-learn/ember-cli-addon-docs#147]
In storefront we wrap the application with some classes [here](https://github.com/ember-learn/ember-cli-addon-docs/blob/7489728ff73a4976b57bee40f9ac992d733932cd/tests/dummy/app/pods/application/template.hbs#L1)

```html
<div class='font-sans text-black leading-normal'>
```

I noticed the line-height was off in @alexlafroscia's docs sites and realized it was because these classes aren't being shared/auto-injected.

How might we set these on the body automatically?

**Comment by pzuraq** [comment]
would it make sense to just use Tailwind's compilation features to add those to `body` directly?

```css
body {
  @apply font-sans text-black leading-norma;
}
```

**Comment by samselikoff** [comment]
Yes I think so. Def an easy step to get this done 👍

**Comment by pzuraq** [comment]
We should also add default link styles while we're at it, currently only markdown links are styled. Makes using `link-to` to go to other pages hard.

**Comment by samselikoff** [comment]
ya we do have a `{{docs-link}}` component that's a subclass of LinkTo but styled. Wanted to try to avoid styling base HTML tags if possible.

**Comment by samselikoff** [comment]
We do this now with Sass's `@extend`.
