### ISSUE TITLE
Support {{docs-logo logo="ember-data"}}

### ISSUE THREAD

**Issue by amiel** [ember-learn/ember-cli-addon-docs#15]
I'm not sure how the svg was generated for `ember` and `ember-cli`, but it'd be great to have one for ![](https://emberjs.com/images/learn/ember-data-e1223a93.png)

**Comment by dfreeman** [comment]
👍  Good call — off the top of my head I know `url-templates`, `factory-guy` and `model-fragments` are all pretty prominent `ember-data-*` addons.

**Comment by amiel** [comment]
As a matter of fact, I'm working on the docs for `ember-data-url-templates` right now :)

I just bought http://www.ember-data-url-templates.com/ to replace the current documentation at https://github.com/amiel/ember-data-url-templates/wiki.

I'm super excited about `ember-cli-addon-docs`, particularly for versioned guides.

**Comment by samselikoff** [comment]
Yep someone should add this! I found the svg logos somewhere, perhaps @locks would know where to get this one?

**Comment by dfreeman** [comment]
Looks like they're all available in an EPS (which Sketch and friends should have no trouble working with) here: https://emberjs.com/logos/

Looking at some of the notices there, though, we probably ought to also include some kind of default boilerplate language somewhere in the docs apps noting non-affiliation.

**Comment by amiel** [comment]
YAY Thank you thank you thank you!
