### ISSUE TITLE
Search input focus too agressive

### ISSUE THREAD

**Issue by anehx** [ember-learn/ember-cli-addon-docs#157]
Hi,

First of all, thanks for this awesome addon. I loved using it and the outcome is really awesome!

IMHO, your policy that pressing "s" anywhere on the page is a bit too agressive.. I'm using this addon to document an addon for forms ([`ember-validated-form`](https://github.com/adfinis-sygroup/ember-validated-form)) and this behaviour makes using the examples next to impossible since my first test value is always "asdf". Also, "/" doesn't work :wink: 

Maybe making the shortcuts configurable would be an option?

**Comment by samselikoff** [comment]
I'm also fine with just making it `/` instead of also `s`

**Comment by yakmada** [comment]
I have to agree with this.  I absolutely love this addon.  We have used it for a few things, but just recently started using it to document a collection of input addons.  Every time we play with an input, it focuses search or navigates to another page.  ...we all tend to just type random characters on the middle row. My team wants me to abandon `ember-cli-addon-docs`.  Disabling on input focus would be good. I'd love to see an option to disable keyboard-shortcuts altogether --or at least force them to use a modifier.

Actually, I might be reporting a separate issue.  If I am reading your docs correctly, I am not using `{{docs-keyboard-shortcuts}}`, but I am getting the keyboard issue described above ...or is the component just to show the shortcuts?  

Anyway, thanks for he great work!

-Adam

**Comment by samselikoff** [comment]
https://github.com/ember-learn/ember-cli-addon-docs/pull/165 closes
