### ISSUE TITLE
Error using Ember Data 5.3.4

### ISSUE THREAD

**Issue by barryofguilder** [ember-learn/ember-cli-addon-docs#1581]
I'm in the process of updating my docs app to use Ember Data 5.3.4 (was previously using 5.3.3). When I bump the patch version, I get the following error when I run my docs app:

> Uncaught (in promise) Error: Could not find module `@ember-data/adapter` imported from `ember-cli-addon-docs/adapters/-addon-docs`

![Screenshot 2024-06-28 at 2 06 10 PM](https://github.com/ember-learn/ember-cli-addon-docs/assets/5649106/d2089c8f-0246-4aca-b592-d0e49bfc7fca)

I know that Ember Data 5.3.4 has a lot of changes in it. So I'm not sure if something in that broke this or if addon docs needs to be updated somehow to support 5.3.4. Keeping my Ember Data locked to 5.3.3 removes the error.

**Comment by RobbieTheWagner** [comment]
@barryofguilder could you please try the latest version of ember-cli-addon-docs and let me know if it is working for you now?

**Comment by barryofguilder** [comment]
@RobbieTheWagner I get a different error now when I run my docs app. I bumped my Ember Data to 5.3.9 and addon docs to 7.2.2.

![Screenshot 2024-12-03 at 1 40 14 PM](https://github.com/user-attachments/assets/e273f63f-0018-4ac0-a8a5-f050d2b4dc78)

**Comment by RobbieTheWagner** [comment]
@barryofguilder does it help if you install `ember-inflector`? Perhaps that is a peerDep?

**Comment by barryofguilder** [comment]
@RobbieTheWagner yep, that fixed it. My docs are now running without any errors using the latest `ember-cli-addon-docs` and `ember-data` 5.3.9. Thanks!

**Comment by RobbieTheWagner** [comment]
Nice, glad things are working now!
