### ISSUE TITLE
Deploy of addons with scoped package names does not work

### ISSUE THREAD

**Issue by Dhaulagiri** [ember-learn/ember-cli-addon-docs#172]
With a scoped package (name of `@my-org/my-addon` in package.json), when I deploy to github I can access my deployed app at `https://my-org.github.io/addon-name/branch-name`, however the index.html is trying to load my assets from `https://my-org.github.io/@my-org/addon-name/branch-name/assets/vendor-faad36ef44bea20afd2cfc9b472e6b19.css`.  The assets do exist at `https://my-org.github.io/addon-name/branch-name/assets/vendor-faad36ef44bea20afd2cfc9b472e6b19.css`

Is there some way to configure this, or should we not be building the scoped package name into the assets path?

**Comment by josemarluedke** [comment]
I run into the same problem. I solved by adding the following in `config/deploy.js`.

```js
let ENV = {
    build: {},
    git: {
      repo: 'git@github.com:myOrgName/myAddonName.git'
    }
  };
```

Home this helps you.

**Comment by Dhaulagiri** [comment]
@josemarluedke thanks, that worked! It's not clear to me if there is a more implicit way we could deal with this so I guess I'll leave the issue open for now 🤷‍♂️

**Comment by dfreeman** [comment]
Thanks for reporting this, @dhaulagiri! Up to now we've been somewhat inconsistent about what we use as the source of truth for the URL, but the 0.4.2 release that just went out takes a firm stand: it tries to derive the name from the `repository` field in your `package.json` first, and then falls back to the addon name if that's unavailable. So as long as you've got your `repository` set (and there are lots of other benefits to that, like EmberObserver linking), you should be good to go without needing to do anything special in your deploy config.

Note also that the static root segment of the URL [is now explicitly configurable](https://ember-learn.github.io/ember-cli-addon-docs/latest/docs/deploying#getrooturl-), if you ever do need to make it something different from your repo name.

**Comment by Dhaulagiri** [comment]
@dfreeman 0.4.2 works perfect without needing to specify any config
