### ISSUE TITLE
Unable to change ember-ace options. 

### ISSUE THREAD

**Issue by GCheung55** [ember-learn/ember-cli-addon-docs#185]
I was trying to add support for editing and beautifying JSON as part of my demo.

Setting `ace` options in the my addon’s `ember-cli-build.js` file doesn’t override the options defined by `ember-cli-addon-docs`.

**Comment by dfreeman** [comment]
@GCheung55 ember-ace should probably handle merging multiple sets of configuration more gracefully, but I believe we're planning to drop our usage of it (the `live-example`) component in the next breaking release of addon-docs, which should hopefully make the issue moot.

**Comment by GCheung55** [comment]
@dfreeman Thanks for the clarification. Digging into the current version of `ember-cli-addon-docs` I'm using, I was able to make it work by overwriting the ace configuration by importing `ember-cli-addon-docs/index.js` within my `ember-cli-build.js`. Since the usage of `ember-ace` is being dropped, I'll adjust.

**Comment by dfreeman** [comment]
👍 That should work for the time being, and then when we release `0.5.0` you should be able to move the config back into your `EmberApp` body
