### ISSUE TITLE
Copy button not found

### ISSUE THREAD

**Issue by ming-codes** [ember-learn/ember-cli-addon-docs#20]
Missed check in?

**Comment by mikemunsie** [comment]
I dug into the source and found that this package is missing the dependencies: `ember-cli-clipboard`. Adding that in removed that error and I can see the copy button. 

Still in the progress of trying to get a snippet to show, but this is one step closer.

**Comment by mikemunsie** [comment]
Heads up: https://github.com/ember-learn/ember-cli-addon-docs/pull/23 will take care of this issue. Once it's merged, copy button and snippets are good to go.
