### ISSUE TITLE
New component that renders API docs for a project

### ISSUE THREAD

**Issue by gossi** [ember-learn/ember-cli-addon-docs#204]
For now `{{docs-viewer.nav}}` helds the API reference. I propose to decouple this into a separate component:

```hbs
{{! /addon/components/docs-viewer/x-api}}

{{!-- Autogenerated API docs --}}
      {{#if (gt project.modules.length 0)}}
        {{docs-viewer/x-section 'API Reference' style='large'}}

        {{#each-in project.navigationIndex as |type items|}}
          {{docs-viewer/x-section type}}

          {{#each items as |item|}}
            {{docs-viewer/x-nav-item (break-on item.name '/') (concat root '.api.item') item.path}}
          {{/each}}
        {{/each-in}}
    {{/if}}
```

Which will be invoked as `{{docs-viewer.api @project=myProject @root='myproject'}}`. It wouldn't even change the way the current component works, it just invokes the new component.

This would change the flexibility in which we can create docs. Some which I would need at the moment, because I run into this ;)

**Comment by RobbieTheWagner** [comment]
I'm closing some old issues. If you think this is still valid, please feel free to open an updated issue and we can try to prioritize it.
