### ISSUE TITLE
Could not find module `dummy/snippets`

### ISSUE THREAD

**Issue by mikemunsie** [ember-learn/ember-cli-addon-docs#21]
Hey guys,

Fantastic work so far! I'm currently beta testing your addon and when I tried to use the `docs-snippet` component, I'm getting this error:

```js
Could not find module `dummy/snippets` imported from `ember-cli-addon-docs/components/docs-snippet/component
```

My template has something like this:

```handlebars
{{#docs-snippet name="your-snippet-name"}}
  {{my-component}}Hello World!{{/my-component}}
{{/docs-snippet}}
```

Any ideas? Perhaps I missed a config?

**Comment by ming-codes** [comment]
You need to install ember-code-snippet. It needs be moved to dependencies.

**Comment by mikemunsie** [comment]
Yep, confirmed! I moved it into a dev dependency and I was able to remove that error. Now I get the error:

```Assertion Failed: A component or helper named "copy-button" could not be found``` 

@ming-codes I'm assuming that's in relation to: https://github.com/ember-learn/ember-cli-addon-docs/issues/20?
