### ISSUE TITLE
Adblock thinks `ad-` means ad

### ISSUE THREAD

**Issue by aaxelb** [ember-learn/ember-cli-addon-docs#215]
With #212, there are classes all over that start with `ad-`, which [sets off alarms in some adblocking software](https://stackoverflow.com/questions/14079048/adblock-plus-hids-elements-with-ids-or-class-with-the-word-ad). Some of the [accused](https://easylist-downloads.adblockplus.org/easylist.txt) include `.ad-sticky` and `.ad-block`, funnily enough.

You should choose a less suspicious prefix.

**Comment by pzuraq** [comment]
How about `docs-`? Unlikely it’ll collide, though I suppose there is still a possibility

**Comment by samselikoff** [comment]
yeesh haha... that's a drag.

I really would love to be able to ship our css obfuscated. I think between purgecss and postcss we can have our cake and eat it too – use unprefixed tailwind classes within addon-docs (with our own config), and then transform them at build-time so consumers are none the wiser.

**Comment by samselikoff** [comment]
https://github.com/ember-learn/ember-cli-addon-docs/pull/224 closes
