### ISSUE TITLE
this.parent.name is not a function

### ISSUE THREAD

**Issue by mikemunsie** [ember-learn/ember-cli-addon-docs#22]
When I pull this repo into my project and start it up, the first thing I get is `this.parent.name` is not a function. After inspection, I found the parent.name is returning a string. Also, there's no such method as `findAddonByName`. 

I can get around this by modifying the index.js and ignoring that logic for now, but any ideas as to why I'm seeing this?

**Comment by dfreeman** [comment]
I'm guessing you have addon-docs in `dependencies` instead of `devDependencies`? We should handle that case more gracefully, but in general you wouldn't have an addon like this in `dependencies` since consuming apps shouldn't need it.

**Comment by mikemunsie** [comment]
(facepalm) Yep that fixed it!! I completely forgot to move this into the devDependencies. I'm actually testing all this out by using yarn and pointing to this repo. Thanks!
