### ISSUE TITLE
Design updates

### ISSUE THREAD

**Issue by samselikoff** [ember-learn/ember-cli-addon-docs#234]
![image](https://user-images.githubusercontent.com/2922250/44767643-b8ac2400-ab2c-11e8-8a6e-c1354e442672.png)

Notables:

- subnavs indent. We should support nested indents of arbitrary depth. We should also option for these navs to be collapsible (future enhancement).
- docs nav on left-hand side has off-white background. Keeps focus on content, creates spacial differentiation between nav & main content area. (current design has too much white & no natural flow for eye to follow.)
- primary color accent for top bar & links. Should be customizable. Can be done later but this would be the direction.
- Separate Guides and API reference as top-level nav items. Can be done later after design tweaks, but direction.

---

Let me know if this looks good & I can implement!

---

Future:

- [ ] Add color, make it customizable
- [ ] Collapsible side navs
- [ ] Separate Guides and API Reference

**Comment by dfreeman** [comment]
I'm on board — particularly like the idea of a configurable accent color to give a bit of customizability while maintaining a consistent out-of-the-box look and feel across docs sites.

This may point more toward the whole meta-site concept we've talked about, but where do you imagine different 'projects' (e.g. the Sandbox section of our docs site today) fitting into this design?

**Comment by josemarluedke** [comment]
I like the overall changes. I also like the move of API reference to its own page. The only thing I would change is the off-white color of the sidebar, the color doesn't seem to fit the rest of the page. Maybe the background color of the code block would make more sense. I do understand that colors are a personal taste, so making that configurable would be awesome.

👍

**Comment by samselikoff** [comment]
@dfreeman I think we'll keep the yielded `link` from `<header>`, so folks can add their own heading links. In AddonDocs' case we'll put the sandbox there. (I think we've also discussed moving the sandbox off the main site and putting it elsewhere.)

Have not thought much about meta site yet :) 

@josemarluedke thx! Yeah I think we can tweak the light-grey but I would like to find something that is standard, imo I don't see that as being configurable. It should just be part of a good baseline typography/styles that everyone gets (and that we can control). I think we can iterate towards something everyone will like. (Dark mode could also help out here.)

**Comment by pzuraq** [comment]
👍 I like the new design, accent color looks awesome and is a nice touch, and I think moving the API docs is great! I could go either way with the sidebar, I kind of like the light grey.

I do think it'd be good to start thinking about how we would want to do the meta site, but I don't think we should block on that. Feel free to merge, you have my vote!
