### ISSUE TITLE
Migration breaks docs

### ISSUE THREAD

**Issue by anehx** [ember-learn/ember-cli-addon-docs#238]
The migration which is run when updating to `v5.1.0` broke the whole documentation in various of my ember addons. The problem is that in the `index.html` files the asset paths are missing the `/versions` prefix. Also, the root level `index.html` still has `/latest` in its asset paths.

This is the commit which applied the migration in one of my addons: https://github.com/adfinis-sygroup/ember-validated-form/commit/2986c04326addc842f5af0c84c63ac1429057881

Did I miss something or is it really broken?

**Comment by samselikoff** [comment]
@anehx Sorry about that! Sounds frustrating.

@ef4 @dfreeman any ideas how to diagnose here?

**Comment by miguelcobain** [comment]
Also having the same issue. Here's the commit that broke.

https://github.com/miguelcobain/ember-yeti-table/commit/a64084a8a37be14362438b7fb04444c3d37f984d

**Comment by rwwagner90** [comment]
@miguelcobain is this still an issue?

**Comment by miguelcobain** [comment]
I don't think so. Let's close for now.
