### ISSUE TITLE
`Tree cycle detected` when upgrading to ember-cli 3.4

### ISSUE THREAD

**Issue by sammynave** [ember-learn/ember-cli-addon-docs#239]
First, thanks for the great addon! We've been using it for a while and love it. 

I tried to update one of our addons to ember-cli 3.4.1 this morning and got a `Tree cycle detected` build failure. The stack seemed quite unhelpful but I was able to narrow it down to `ember-cli-addon-docs`.

There was a similar issue happening in [ember-auto-import](https://github.com/ef4/ember-auto-import/pull/90) so maybe there's a clue there?

I have a repro here: https://github.com/sammynave/tree-cycle-repro if that's helpful. You should just be able `yarn && ember s` to get the error.

Let me know if I can provide any more info.

Thanks!

**Comment by dfreeman** [comment]
Hi @sammynave — thanks for the report!

For the moment I think the `latest` dist tag for ember-cli has been rolled back to `3.3.0`. It's definitely possible we'll have to do some work on this end, but I think we should likely wait for things to settle down on that side first.

**Comment by sammynave** [comment]
Quick update, just bumped ember-cli in the reproduction repo to 3.4.2 and it's still broken : /

**Comment by dfreeman** [comment]
Thanks for the update. Looking more closely at [the PR in ember-auto-import](https://github.com/ef4/ember-auto-import/pull/90), it looks like this isn't a trivial fix. I don't think I'm personally likely to be able to get to it within the next week or so, unfortunately 😕 

If anyone has the opportunity take a pass at fixing it in the meantime, we have roughly the same issue as `auto-import` did: we're doing an analysis of the templates during their preprocessing and then using that result to populate our `public` tree (specifically the search index JSON document). I suspect a similar approach to `auto-import`'s solution is viable here, too.

**Comment by nightire** [comment]
Just did a simple test to make sure the problem is with `SearchIndexer`.

If simply removes it from the public tree, the problem can be solved temporarily, of course you will lose the ability to search.

The next step would be to go deeper into `SearchIndexer` to see if I can identify a pattern similar to [the PR in ember-auto-import](https://github.com/ef4/ember-auto-import/pull/90). If I can make some progress (I wish 🙏🏻), I will try to submit a PR.

**Comment by dfreeman** [comment]
A quick note that occurred to me this morning: unlike auto-import, we might be able to use `postprocessTree('all')`, because we only ever expect to be run as a top-level dependency.

**Comment by villander** [comment]
I have the same issue, after that I tried update to 3.4.2 =/
