### ISSUE TITLE
Markdown files are not capturing Snippets

### ISSUE THREAD

**Issue by mikemunsie** [ember-learn/ember-cli-addon-docs#25]
For some reason the Snippets plugin is only finding snippet-templates in the `.hbs` files. You would think after a `.md` file is transformed into a `.hbs` file it would work, but apparently something is up. 

Investigation in progress... 🔍

**Comment by mikemunsie** [comment]
Turns out it's more of a configuration issue with the **code-snippet** plugin. They look at the src folder and then find files matching extensions: `js|coffee|html|hbs|css|sass|scss|less|emblem`. I went ahead an added a PR to support .md files as a temporary fix till you can configure those. 

See: https://github.com/ef4/ember-code-snippet/pull/40/files

If that gets merged, we can update the dependency and hopefully support `.md` files with snippets!

**Comment by dfreeman** [comment]
Fixed by #28.
