### ISSUE TITLE
Make use of <AngleBrackets/>

### ISSUE THREAD

**Issue by gossi** [ember-learn/ember-cli-addon-docs#262]
Because they look soo much better than curlies for components. Second is to be prepared for them. Docs use positional components with curly braces and if you want to use angle brackets we need to know the params by name.

**Comment by josemarluedke** [comment]
Huge +1 on this. I think it would make addon docs much nicer.

**Comment by Panman82** [comment]
With the push towards Ember Octane (nearly out), and the push to get addons to document "their Octane ways", I would think this *has* to be climbing up the priority list...

**Comment by rwwagner90** [comment]
This issue is unclear to me. Is it asking that we convert our own internal docs to use angle brackets?

**Comment by Panman82** [comment]
@rwwagner90 Humm... my thought was that anything emitted by this addon to show component usage would show it with `<AngleBrackets>`. Perhaps #195 is a bit more clear/direct.?.

**Comment by rwwagner90** [comment]
I think there are several spots that could use conversions

**Comment by miguelcobain** [comment]
Did https://github.com/ember-learn/ember-cli-addon-docs/pull/1016 fix this?

**Comment by rwwagner90** [comment]
@miguelcobain I think this is about updating our internal docs to use angle brackets everywhere. I think there are still lots of examples to update. For example https://github.com/ember-learn/ember-cli-addon-docs/blob/master/tests/dummy/app/templates/docs/components/docs-header.md

Would you be interested in helping convert the docs to angle bracket? I could really use help with this addon.

**Comment by miguelcobain** [comment]
@rwwagner90 I will try to give that a shot this week. 👍

**Comment by rwwagner90** [comment]
@miguelcobain is there anything remaining for this?

**Comment by miguelcobain** [comment]
@rwwagner90 nope. We should be all-in on angle brackets now.
