### ISSUE TITLE
Issues with empty rootURL

### ISSUE THREAD

**Issue by tempo22** [ember-learn/ember-cli-addon-docs#265]
When using a custom domain for a project app, i'm overriding the `getRootURL()` function as stated in the [docs](https://ember-learn.github.io/ember-cli-addon-docs/docs/deploying#getrooturl-)

However, this create incorrect assets path in the index.html because of this line: 
https://github.com/ember-learn/ember-cli-addon-docs/blob/731830a208e6a36562a4639867439649720a032a/lib/deploy/plugin.js#L156

With `let rootURL = [this._getRootURL(), appRoot].filter(Boolean).join('/');` set to an empty string, the asset path become `//assets...` which is considered as a domain.

Is there a quick work around for this ?

**Comment by tempo22** [comment]
It seem that the 404.html page segment count is also incorrect because of this:
https://github.com/ember-learn/ember-cli-addon-docs/blob/731830a208e6a36562a4639867439649720a032a/lib/deploy/plugin.js#L67

`segmentCount` is set to 1 when `rootURL` is an empty string while the [comments on the 404.html](https://github.com/ember-learn/ember-cli-addon-docs/blob/731830a208e6a36562a4639867439649720a032a/vendor/ember-cli-addon-docs/404.html#L24) say that it should be left to 0

**Comment by dfreeman** [comment]
This should be fixed in v0.6.2
