### ISSUE TITLE
API Docs: classes in modules

### ISSUE THREAD

**Issue by anehx** [ember-learn/ember-cli-addon-docs#267]
Currently, if we have a class in a module e.g `my-addon/lib/some-class.js` which looks like this:

```js
/**
 * Some class which does some stuff..
 *
 * @class SomeClass
 */
export default class SomeClass {
  /**
   * Some method which magically always returns 42
   *
   * @method someMethod
   * @return {Number} Always 42
   */
  someMethod() {
    return 42
  }
}
```

As a user I'd expect to see this class documented the same as if it was located in `my-addon/service/some-service`. I'd expect to see the documented properties, accessors, methods etc.

What do you think about this? Is there a reason that this is implemented like this?

**Comment by samselikoff** [comment]
I have some code for this, just need to get back around to it. I think we'll be able to support these "special cases".
