### ISSUE TITLE
Delete gh-pages branch

### ISSUE THREAD

**Issue by allthesignals** [ember-learn/ember-cli-addon-docs#268]
How do I delete the `gh-pages` branch? I have upgraded from `0.5.0` to `0.6.0`, deployed, and now my documentation site is kaputt (it is trying to load assets from `/latest/assets`, which I understand was changed for some reason). My strategy now is to just blow out `gh-pages` and start over. But that doesn't work.

```
$ git branch -D -f gh-pages
error: Cannot delete branch 'gh-pages' checked out at '/Users/mgardner/deploy-ember-mapbox-composer'
```

I tried `rm -rf` the deploy folder. 

This has happened before, and it required me to go into my `.git` folder, but I don't remember how to do that and I don't want to ruin my repository. 

I could try to _revert_ the deployment, but I can't checkout the branch:
`fatal: 'gh-pages' is already checked out at '/Users/mgardner/deploy-ember-mapbox-composer'`

Any idea what is happening?

**Comment by pzuraq** [comment]
So git has checked it out at that local location, a different folder, and just deleting the folder doesn't tell git it's no longer checked out. I've run into this before, and I think I followed these directions: https://stackoverflow.com/questions/41545293/branch-is-already-checked-out-at-other-location-in-git-worktrees

**Comment by allthesignals** [comment]
Thanks @pzuraq - looks like `rm -rf ../deploy-{your-repo-name} && git worktree prune` will do the job should you ever need to "start over" on the deployment.
