### ISSUE TITLE
Documentation is not being generated

### ISSUE THREAD

**Issue by tstormk** [ember-learn/ember-cli-addon-docs#272]
Hello

We've just started using this addon for our company styleguide. I've been testing the addon with one of components (we need to migrate our documentation as it was previously just written out in pages, not stored in ESDoc comments as it's going to be now). Here's the code for the documentation:

```
/**
  This component provides an interface for defining a standard button UI element.

  @class Button
  @public
*/
export default Component.extend({
  ...

  /**
    The path to the icon to display in the button.

    @argument icon
    @type String
  */
  icon: null,

  /**
    The size of the icon displayed by the `icon` argument.

    The Icon documentation for accepted values.

    @argument iconSize
    @type String
  */
  iconSize: 'small',

  /**
    When true, the Button is displayed with a contrasting color scheme in order
    to indicate to the user that the Button action is destructive.

    @argument isDestructive
    @type Boolean
  */
  isDestructive: false,

  /**
    Indicates whether button is disabled or not. Defaults to false.

    @argument isDisabled
    @type Boolean
  */
  isDisabled: false,

  /**
    Indicates whether the button should displays its loading state. When
    loading, the button displays a Spinner instead of its regular content.

    @argument isLoading
    @type Boolean
  */
  isLoading: false,

  /**
    When true, the Button is displayed without the regular button styling,
    instead appearing more like a link than a button.

    @argument isPlain
    @type Boolean
  */
  isPlain: false,

  /**
    Indicates whether the Button is a primary action. When a Button is primary,
    it is displayed with a highlight in contrast to secondary actions.

    @argument isPrimary
    @type Boolean
  */
  isPrimary: false,

  /**
    When true, the Button type becomes 'submit' instead of just being a regular
    button. This feature is usually used in conjunction with Forms.

    @argument isSubmit
    @type Boolean
  */
  isSubmit: false,

  /**
    The size of the button. Defaults to 'large'.

    Accepts values 'slim' and 'large'.

    @argument size
    @type String
  */
  size: DEFAULT_SIZE,

  /**
    The text to display in the button content. Alternatively, button content can
    be passed through the Button component block.

    @argument text
    @type String
  */
  text: null,

  /**
    When true, the Button will take up the full width of its container.

    @argument useFullWidth
    @type Boolean
  */
  useFullWidth: false,

  /**
    A hook that is triggered when the Button is clicked.

    @function onClick
  */
  onClick() {},

  /**
    A hook that is triggered when the Button is focused.

    @function onFocus
  */
  onFocus() {},

  /**
    A hook that is triggered when the Button is blurred.

    @function onBlur
  */
  onBlur() {},

  ...
});
```

I've based this on the way the documentation is written out in the `ember-cli-addon-docs` dummy app.

Unfortunately, the documentation AST being generated by the addon does not match the structure above. It does not register the Component nor its arguments. If I change the Component to be declared as a const and then proceed to export that, it registers the Component itself, but still not the arguments:

```
const Button = Component.extend(...);

export default Button;
```

As far as I can tell it's ESDoc that is the problem. I've walked through the code in the `ember-cli-addon-docs-esdoc` addon and it seems to be running perfectly, except ESDoc is not generating the documentation properly.

I'm at a loss as to what I'm doing wrong. As far as I can tell the way my documentation is set up is the exact same as the way it's set up in the dummy app here. I also followed the steps in the Usage guide (I am implementing a custom way of displaying the documentation generated, but as far as I can see that shouldn't affect how ESDoc generates the documentation).

Any help would be appreciated.

**Comment by pzuraq** [comment]
Unfortunately ESDoc is only capable of working with native class syntax. It is a very powerful tool, but it doesn't have any real support for custom class models, which makes sense - moving forward, there won't be a reason to support them.

This is why we've also made the YUIDoc plugin. Since YUIDoc is based entirely on comments, it will work with _any_ custom class system, and will work with the classic EmberObject model until it is phased out.

**Comment by pzuraq** [comment]
Should also note a couple things about your example:

* ESDoc actually does static analysis of your code, so you wouldn't need to add most of those tags if you were using it:

    ```js
    /**
      "@class" isn't necessary here, it knows that this is a comment for a class
    */
    export default class Button extends Component {
      /**
        These tags will still be necessary, though we do support pulling that 
        information from decorators as well (e.g. @ember-decorators/argument).
        However, you _don't_ need to restate the name of the field, `icon` will
        be pulled from the code via static analysis.

        @argument
        @type String
      */
      icon = null;

      //...

      /**
        No need to label this either, it understands that it is a method
      */
      onClick() {}

      //...
    }
    ```

* With YUIDoc, you should actually be tagging methods with `@method`. We do have some custom tags setup, you can check them out on [the documentation plugin's readme](https://github.com/ember-learn/ember-cli-addon-docs-yuidoc)

    ```js
    /**
      A hook that is triggered when the Button is clicked.

      @method onClick
    */
    onClick() {},
    ```

Native classes are definitely preferable from a docs/tooling standpoint, but they are also the cutting edge in Ember right now. We _are_ landing the native class RFC implementation in 3.6, so classes _without_ decorators will be stable, but without decorators they aren't very useful 😕 you can rely on projects like `ember-decorators` which are stable, but there could still be changes in the spec itself, so it's a little risky.
