### ISSUE TITLE
Assertion Failed: DocsRoutes wasn't able to correctly detect the current route

### ISSUE THREAD

**Issue by gossi** [ember-learn/ember-cli-addon-docs#287]
This error message originates from the `docs-routes` service:

https://github.com/ember-learn/ember-cli-addon-docs/blob/a462b45971e4d873187854c71bb8169a78176510/addon/services/docs-routes.js#L50

Actually I don't use `AddonDocsRouter` nor do I use `docsRoute` from `ember-cli-addon-docs/router.

**Comment by rwwagner90** [comment]
@gossi @mike-engel I believe it is required that users use `AddonDocsRouter` if they want to use this addon, and I also think `locationType: 'auto'` is recommended. I am going to close this as out of scope, as I don't think it is a bug, just a requirement of using the addon.
