### ISSUE TITLE
Build Error (Rollup): Couldn't find preset "env" relative to directory

### ISSUE THREAD

**Issue by allenylzhou** [ember-learn/ember-cli-addon-docs#297]
I set up a yarn workspace project, where I ran these commands:
1. `cd packages && ember addon some-addon`
2. `ember install ember-cli-addon-docs`
The resulting project can be found here: https://github.com/allenylzhou/yarn-workspace-sandbox/tree/ember-cli-addon-docs

Steps to reproduce the problem can be found in the README of the above project; long story short, if I run ember serve, I end up with this error:
```
Build Error (Rollup)

Couldn't find preset "env" relative to directory "/var/folders/gm/vmqc_9h12rs2rvmy3y_c63km0000gn/T/broccoli-8749nhrbBQTsRq0k/cache-069-rollup/build/src"


Stack Trace and Error Report: /var/folders/gm/vmqc_9h12rs2rvmy3y_c63km0000gn/T/error.dump.0fcbc84e6aab3adc7a6bf52b48282123.log
```

I've also determined that the culprit is ember-cli.
If I change
`"ember-cli": "~3.6.1",`
to
`"ember-cli": "~3.4.4",`
the problem goes away.

This problem also only occurs in the context of a yarn workspace: https://yarnpkg.com/lang/en/docs/workspaces/

**Comment by alexlafroscia** [comment]
This is do to this `ember-fetch` bug:

https://github.com/ember-cli/ember-fetch/issues/156

There is a commit on `master` that bumps the `ember-fetch` version to one that doesn't cause this error, but that hasn't actually been published yet in an NPM release 🤷‍♂️ 

If you are using `yarn`, you can put this in your root-level `package.json` to fix the problem

```diff
{
+  "resolutions": {
+    "**/ember-fetch": "^6.2.0"
+  }
}
```

And it should fix the problem.
