### ISSUE TITLE
Inconsistent version dropdown

### ISSUE THREAD

**Issue by alexlafroscia** [ember-learn/ember-cli-addon-docs#317]
The version picker in the top-level nav bar doesn't always give you the same list of deployments. The initial render provides a full list, be subsequent renders provide a limited set.

![kapture 2019-02-05 at 11 32 30](https://user-images.githubusercontent.com/1645881/52299290-e1391500-2939-11e9-9d98-91d87c8027b2.gif)

You can see this live here:

https://alexlafroscia.github.io/ember-rx/

**Comment by dfreeman** [comment]
I _think_ this should be fixed by https://github.com/ember-learn/ember-cli-addon-docs/pull/309

**Comment by alexlafroscia** [comment]
Cool! I'll verify when a version is released that includes that fix.

**Comment by samselikoff** [comment]
@alexlafroscia could you try v0.6.4?

**Comment by alexlafroscia** [comment]
Yup, seems to be fixed!

https://alexlafroscia.github.io/ember-rx/versions/master/

**Comment by samselikoff** [comment]
Sweet! Docs look great 👌
