### ISSUE TITLE
Add info about router-scroll configuration

### ISSUE THREAD

**Issue by samselikoff** [ember-learn/ember-cli-addon-docs#34]

**Comment by dfreeman** [comment]
Does this just mean recommending using `ember-router-scroll`? The 404 redirect shenanigans to avoid needing to use `locationType: 'hash'` should all be automated now.

**Comment by samselikoff** [comment]
A bit more - to use `ember-router-scroll` with our `{{docs-viewer}}` component, you need to [just a bit of wiring](https://github.com/ember-learn/ember-cli-addon-docs/blob/master/tests/dummy/config/environment.js#L11-L13):

```
routerScroll: {
  scrollElement: '#docs-viewer__scroll-body'
}
```

**Comment by samselikoff** [comment]
This might change after the redesign... I'd like to make the `<body>` always be the main scrolling element

**Comment by samselikoff** [comment]
Not needed anymore
