### ISSUE TITLE
ember-octane compatibility

### ISSUE THREAD

**Issue by MichalBryxi** [ember-learn/ember-cli-addon-docs#340]
I tried to play with `ember-octane` [preview](https://github.com/ember-cli/ember-octane-blueprint) and I got into troubles with some internal dependencies of this project. I did not even finish the [quickstart guide](https://ember-learn.github.io/ember-cli-addon-docs/docs/quickstart). Not sure whether this is octane or ember-cli-addon-docs issue.

The way to reproduce this:
```
git clone https://gitlab.com/michal.bryxi/ember-safe-button.git -b ember-app-scheduler-build-bug
cd ember-safe-button
yarn
ember s
```

Open: http://localhost:4200 and see that there is following error in the console:

```
loader.js:247 Uncaught (in promise) Error: Could not find module `ember-app-scheduler` imported from `ember-router-scroll/index`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at Class._extractDefaultExport (index.js:413)
...
```

**Comment by nadnoslen** [comment]
Hey @MichalBryxi,

I have been running into another problem altogether (`a computed property key must be a string ... undefined undefined`) when I work through the _Quick Start_ for an Octane addon.

I notice you haven't really followed (and you say finished) the quick start though.  Your `application.hbs` & `index.hbs` should be populated.  I wonder if that is hindering you?  I assume if you keep going until it tells you to start your server you'll get a different error?

Anyway, I'm working on this myself right now and if I see anything helpful I'll pass it on.

**Comment by MichalBryxi** [comment]
Hi @nadnoslen. Hope there is a chance to figure this one out. To clarify:

1. I said I **did not** finish the quickstart. I did finish step no.5: **Create your Markdown templates**. After this I would assume to see some content. 
1. I finished the quickstart up to step no.8: **Launch your docs site**. The same result. I pushed it to the code to the branch mentioned above.
1. If there is anything I skipped from the quickstart that might be important or did wrong, please tell me. I assume all the steps were executed correctly.

**Comment by MichalBryxi** [comment]
Update: I had a theory that `pods` might be the issue here, but even after recreating the whole app without pods the issue persists.

**Comment by MichalBryxi** [comment]
Looks like pinning in my `devDependencies` in `package.json`:

```
    "ember-router-scroll": "github:dollarshaveclub/ember-router-scroll#greenkeeper/ember-app-scheduler-2.0.0",
```

Fixed this issue.

**Comment by MichalBryxi** [comment]
Another observation: When I delete `{{docs-header}}` in my template, then the problem goes away completely.

**Comment by nadnoslen** [comment]
Hey @MichalBryxi,
Yes, I discovered that `{{docs-header}}` was my problem for the `A computed property key must be a string, you passed undefined undefined`.  I stopped tinkering with Octane for my new addon because I was bumping into too many challenges.

**Comment by sirJiggles** [comment]
can confirm, ran into the same issue with octane and pods. removed header worked again. on 0.6.8

**Comment by MichalBryxi** [comment]
For anyone struggling with this: I don't have a cure, but I did:
 1) Disable pods
 2) These changes in [package.json](https://gitlab.com/michal.bryxi/ember-safe-button/commit/d4eac701a6aef13f9a177e2ab7927d49bdec43da#7030d0b2f71b999ff89a343de08c414af32fc93a)

I suspect it might be because of the extra packages that got dragged in because of `ember-concurrency` and/or `ember-animated`. Note that currently I'm using both without a problem. Just needed to adjust my syntax of the decorators somehow (see the app history up to `ember-octane` branch where stuff started to work)

**Comment by dfreeman** [comment]
For what it's worth, I just spun up a fresh octane addon with addon-docs here: https://github.com/dfreeman/octane-addon-with-addon-docs. There are definitely a few odd styling issues and some deprecation warnings, but I'm not seeing any hard errors.

My recommendation would be to ensure that you're:
 - using the latest addon-docs release
 - using the latest ember-concurrency release (double check your `yarn.lock` or `package-lock.json` to ensure you don't have multiple versions floating around that might conflict with each other—you should only see `0.9.0`)

@samselikoff I can't begin to explain why the styling is so weird, though — stuff like the brand color extending to the bottom of the page past the hero component, and all the page content shifting down weirdly when you open the versions dropdown. Any thoughts?

**Comment by samselikoff** [comment]
haha nothing off the top of my head. Will check this out soon.

**Comment by samselikoff** [comment]
The reason is because [here](https://github.com/ember-learn/ember-cli-addon-docs/blob/master/addon/styles/addon.scss#L38) we're using `body > .ember-view` to target the application's wrapping div. It looks like in Octane that div no longer exists. (Which is super cool!)

How might we reliably target this across both styles of app? Could we add a class to the wrapping div in pre-Octane apps, and target that? And, how might we wrap Octane apps in a div we can use to `flex: 1`? (I might be able to redo the css to not require this... I think it would involve removing the bg brand color on the body, and instead just adding it as a top border to the header. Although I kinda like it as a a body bg. Could go either way.)

**Comment by NullVoxPopuli** [comment]
if anyone comes across this issue and has the motivation to fix octane support, the edition utils package have a way of detecting edition:

https://github.com/emberjs/ember-edition-utils#detecting-edition
```ts
const { has } = require('@ember/edition-utils');

if (has('octane', this.project.root)) {
  // do octane stuff
} else {
  // do classic mode stuff
}
```

**Comment by nadnoslen** [comment]
I agree with that @rwwagner90. I say close it.
