### ISSUE TITLE
Install ember-cli-sass

### ISSUE THREAD

**Issue by samselikoff** [ember-learn/ember-cli-addon-docs#35]
Should host app need to install? Its a dependency...

**Comment by ro0gr** [comment]
The best way I can think of is to avoid scss files from the addon. Are there any saas specific features used in this project?

**Comment by ro0gr** [comment]
From a quick review I can see that `ember-cli-addon-docs` is currently using only(?) nested selectors and variables features. 

 - sass variables can be replaced with the css [custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*)(if IE can be abandoned)
 - nested selectors: 
   - has to be denormalized to a css full selectors form. 
   - or maybe `postcss`+`postcss-nested` is an option? it seems like that's a slimmer tool for the task. However the original issue will remain the same - consumer app will be forced to install an additional deps.

**Comment by dfreeman** [comment]
As a side note, I think the [way we're using ember-component-css here](https://github.com/ember-learn/ember-cli-addon-docs/blob/master/index.js#L42-L44) may cause issues with host apps that are also using it, as our config will merge with the host's and possibly lead to Weird Behavior.

If we do wind up revisiting how styles are set up in addon-docs, we may want to look into that potential issue as well.

**Comment by ro0gr** [comment]
> If we just want to use Sass features internally and dump the output in vendor.css

This requires pre-building of css file during the package publish step. I think it's totally doable however it's not clear how to deal with the cases when `ember-cli-addon-docs` is linked into the consumer addon.

> Since the core Ember ecosystem is still supporting IE11 for the foreseeable future, I wouldn't feel super comfortable dropping it in addon-docs.

I hope there are no frontend developers who surf internet and especially addons documentation in IE11 today. I believe that IE11 is supposed to be supported only for the users w/o a tech background from a developing countries.

If that is true we can at least consider usage of custom css props as a part of preprocessor independent public api for docs styling customizations. 

> My general preference as a consumer of addons is that they not bring in their own dependencies with native extensions when possible 

Totally agreed 👍

**Comment by samselikoff** [comment]
I just want to use it to develop addon-docs, not require it as a dependency for host apps.

I was working on ember-data-storefront and the styles for the `<docs-viewer>` component were messed up, until I installed `ember-cli-sass`.

**Comment by dfreeman** [comment]
Normally I'd expect the setup we have here to work without needing to do anything else in the host. I'll see if I can diagnose next time I have a little time to spend hacking on addon-docs.

**Comment by dfreeman** [comment]
@samselikoff FWIW I just dropped addon-docs into an addon I'm developing and `{{docs-viewer}}` and friends all have the right styling without any CSS preprocessor installed in the host...

**Comment by pzuraq** [comment]
Pretty sure this shouldn't be an issue now since all styles are being exported through `addon.scss` which will get compiled fully by this addon. If they styles were in `/app` then it would be different, but I'm pretty sure it should work as is - will test when I update @ember-decorators docs

**Comment by samselikoff** [comment]
agree
