### ISSUE TITLE
Use module name only (drop path) for API Modules nav

### ISSUE THREAD

**Issue by samselikoff** [ember-learn/ember-cli-addon-docs#353]
Here's the Modules section of the nav for Ember Animated:

![image](https://user-images.githubusercontent.com/2922250/55737278-e0346a80-59f2-11e9-9bd6-3a79a0b9249f.png)

 and Ember Decorators:

![image](https://user-images.githubusercontent.com/2922250/55737293-e9253c00-59f2-11e9-9098-6cb870f398d8.png)

I know they're not unique, but what do y'all think of dropping the path from the nav bar?

Here's what it would look like for Ember Animated:

![image](https://user-images.githubusercontent.com/2922250/55739423-022fec00-59f7-11e9-8998-0fb0ea883955.png)

Seems much better! And in the event an Addon exports two modules with the same name, we can figure that out when we hit it? (I have some ideas but in the meantime, I can't find an example of this in the wild).

**Comment by pzuraq** [comment]
I think it would probably be better if we could have some kind of a tiered system, the point of the nav in part is to be a mapping between what people might actually see in some code. While it may be obvious that `@ember-decorators/` is the scope of all the packages, I think people might be confused and think it's `ember-decorators`. Basically, if I go into a file and see `import { foo } from @ember-decorators/object`, it should be dead-simple to find that via the API docs for the library.

So ideally something like:

```
@ember-decorators/
  component
  object
  service
```

**Comment by samselikoff** [comment]
Agreed

**Comment by dfreeman** [comment]
Agreed the tiered approach feels better to me—trying to get too smart and elide information seems like it'll come back to bite us sooner or later when someone lays out their modules in a way we don't anticipate.

Definitely 👍 on cleaning up that section of the nav though!
