### ISSUE TITLE
v0.6.9 broken on new installations

### ISSUE THREAD

**Issue by cah-briangantzler** [ember-learn/ember-cli-addon-docs#356]
I created a new addon and converted it to use ember-cli-addon-docs. I just happened to do this the day after v0.6.9 was released. After following the documentation and doing ember s, the docs page failed here https://github.com/ember-learn/ember-cli-addon-docs/blob/master/addon/components/docs-viewer/x-autogenerated-api-docs/component.js#L61 Since this was a new addon, I did not have any modules defined yet, and this assumes the filter will return at least one element.

I noticed that this entire file was new in this release, so rolling back to the previous release fixed it.

**Comment by sbflynn** [comment]
Had the same issue when upgrading an existing 'component only' addon to 0.6.9.

**Comment by cah-briangantzler** [comment]
0.6.10 has fixed this issue
