### ISSUE TITLE
Snippits containing self-closing angle bracket components break markdown parsing

### ISSUE THREAD

**Issue by jrowlingson** [ember-learn/ember-cli-addon-docs#360]

**Comment by kpatelsecondst** [comment]
Does [this workaround](https://github.com/ember-learn/ember-cli-addon-docs/issues/391#issuecomment-512989450) render self-closing brackets too?

**Comment by crixx** [comment]
Any news on this or other ideas apart from using hbs?

@kpatelsecondst : Nope, the work around doesn't fix this.
The problem is, that after the code-block, markdown doesn't get rendered anymore - it's rendeered inside the code block. 

Here some examples that break the markdown parsing.  

```
<X />

## Header
--
<X class="foo" />

## Header
--
<X class="foo" 
/>

## Header
-- 
<X
@something="something"
/>

## Header
```

**Comment by kpatelsecondst** [comment]
@crixx : My mistake, markdown does indeed break. The only temporary workaround would probably be to use html header tags until markdown parsing is fixed.

**Comment by barryofguilder** [comment]
I think this might still be an issue. We are still seeing this issue for our self closing components in the `demo-example` component.

```handlebars
{{#docs-demo as |demo|}}
  {{#demo.example name="docs-icon-basic.hbs"}}
    <UiIcon @icon="rocket" />
  {{/demo.example}}

  {{demo.snippet "docs-icon-basic.hbs"}}
{{/docs-demo}}
```

The above code will cause any markdown headers below it to not work.

**Comment by samselikoff** [comment]
@barryofguilder I haven't been working on this lately but best bet is probably to open a new issue.

If someone wants to help this project the most important thing is probably to triage/prioritize issues. We should prioritize bug fixes first. Octane stability I would deprioritize until it's stable.
