### ISSUE TITLE
Circle CI - `ember-cli-addon-docs/components/api/x-class/template.js: Worker is terminated`

### ISSUE THREAD

**Issue by nadnoslen** [ember-learn/ember-cli-addon-docs#367]
I'm just noticing some build issues as I am upgrading a number of my addons.  I'm getting this strange _Worker is terminated_ message from Broccoli & Babel.

This error presented itself when I upgraded my addon to Ember-3.10 and when installed the latest `ember-cli-addon-docs@0.6.12`.

I've downgraded to `ember-cli-addon-docs@0.6.10` and continue to receive the error.

For some reason, it's complaining about the `x-class` component here in `ember-cli-addon-docs`.

Here's a snippet of the error:

```
codeFrame: Worker is terminated
  - errorMessage: ember-cli-addon-docs/components/api/x-class/template.js: Worker is terminated
        in /tmp/broccoli-146OQkJi1r3RjNz/out-296-broccoli_persistent_filter_template_compiler
        at broccoli-persistent-filter:Babel > [Babel: Modules for Templates] (Babel: Modules for Templates)
  - errorType: Build Error
```

[And if you are interested in the full error output, find it here at the build job](https://circleci.com/gh/cybertooth-io/ember-simple-auth-okta/252).

Anyone else seeing anything like this or have any suggestions?  I'm kind of stumped. 🤷‍♂️

**Comment by dfreeman** [comment]
@nadnoslen when I've run into that error in the past, it's been because there were too many parallel Babel workers starting up in Circle. The [default Travis configuration](https://github.com/ember-cli/ember-new-output/blob/aa931914d0aa436b8a84f07c41ce28b0395c7603/.travis.yml#L17-L19) sets `JOBS=1` to avoid this, and I typically do the same in Circle.

**Comment by nadnoslen** [comment]
Hey @dfreeman, thanks so much for the reply.  I'll tinker with that this morning to see if it helps and post results or changes here.  Cheers.

**Comment by nadnoslen** [comment]
Hey @dfreeman, thanks for the tip.  It got me looking into other people's CircleCI setups and I resolved it by setting the `JOBS` environment variable to `2`.  I expect I may need to lower this to 1 like as suggested in the `.travis.yml` that ships with Ember projects; as of now I'll leave it at 2.

TLDL:
```yaml
# ...
    docker:
      - image: circleci/node:lts-browsers
        environment:
          JOBS: 2
# ...
```

Thanks again!
