### ISSUE TITLE
Enforce a hard boundary between addon and docs

### ISSUE THREAD

**Issue by ef4** [ember-learn/ember-cli-addon-docs#383]
I think we really need a hard boundary between the addon and the addon's docs site.

Addon development is different from app development because apps can choose when and how to deal with deprecations and compatibility problems, whereas (well-maintained) addons need to be very aggressive about those things. Addons generally need to be the first to update to the latest and greatest, before apps can follow. This creates a chicken-and-egg problem for AddonDocs, because it's an app that blocks addon development.

There is also the problem of AddonDocs altering the environment that your addon will be tested in. Do your addon's components accidentally depend on Tailwind's CSS reset? How would you test your addon under a new Ember optional feature that isn't supported by AddonDocs yet? Does your addon accidentally depend on helpers that are only present because AddonDocs uses them?

All of this leads me to the conclusion that we need to split the AddonDocs site into a standalone Ember app.

From a package management standpoint, this is cleanest if you use a monorepo. But there are two major downsides to monorepos that I think mean we can't force them upon everyone:

 - NPM is incapable of depending on an exact commit of a package in a monorepo (people have been complaining about this [since 2012](https://github.com/npm/npm/issues/2974))
 - hiding your addon down inside a package is definitely confusing when first approached. There is an aesthetic objection that's not wrong.

So instead we probably need to put a separate app in a `/docs` subdirectory. That app has its own package.json and yarn.lock, completely separate from the containing addon. While that gives you one more thing to update, it does come with benefits, such as letting you put off upgrading your docs site to a newer ember version even though you've already updated your addon itself to support and test under that version.

In `/docs/package.json`, if the author has chosen to use `yarn` we can use a `link:` dependency on the addon itself, and then everything Just Works. If the author is using NPM, we can use a `file:` dependency, which works correctly but won't give you live updating during development (because it make a copy of the addon, rather than linking to it). In that case we could provide a post-install step that creates a link instead.

It would probably not be a big deal to also support the monorepo use case, for people who actually want that. I don't think it's worth adding complexity for, but if we design things correctly it's not actually more work. AddonDocs just needs to accept an argument for "what is the path to the actual addon you are documenting" so it can find source code to generate API docs from, etc.

**Comment by buschtoens** [comment]
I couldn't agree more! This also more elegantly solves the awkward situation multi-package addons, like `@ember-decorators` are in: Where do you put the "main" docs and how do you pull in / mount the individual package API docs?

I am also _constantly_ running into [trouble with CI](https://travis-ci.org/ember-decorators/ember-decorators/builds/554217966) that is failing only because of AddonDocs and the dependencies it pulls in.

**Comment by samselikoff** [comment]
Realized I never commented here, but Ed and I had several conversations re: this topic.

I'm 100% on board with this!
