### ISSUE TITLE
ember-cli-addon-docs styles interfering with my addon that uses Tailwind

### ISSUE THREAD

**Issue by barryofguilder** [ember-learn/ember-cli-addon-docs#395]
The addon I'm working on is a component library that uses Tailwind 1.0 for styling. It seems that `ember-cli-addon-docs` uses Tailwind as well, but updates some styles for the markdown files for unordered lists, etc. This causes an issue with my components due to the CSS specificity rules.

For example, my tab components use unordered lists which contain the following markup:
```handlebars
<ul>
  <li class="-mb-px mr-2">{{yield}}</li>
</ul>
```

When I inspect the applied CSS to my component inside the `docs-demo` component, I see this:

<img width="342" alt="Screen Shot 2019-07-11 at 4 33 07 PM" src="https://user-images.githubusercontent.com/5649106/61083416-b0ce3900-a3f9-11e9-928e-7293dcb95429.png">

Notice that the class of `-mb-px` is being ignored due to the specificity of `.docs-md li`.

The way I'm currently getting around this is adding a class to the `demo-example` component, then adding a more specific override in my stylesheet:
```handlebars
{{#demo.example name="docs-tabs-basic.hbs" class="code-snippet"}}
  ...
{{/demo.example}}
```
```css
.code-snippet .-mb-px {
  margin-bottom: -1px;
}
```
Is there any way to get around this? My workaround seems really error prone and I'd have to add overrides for any other additional bottom margins to `li` in the future.

**Comment by barryofguilder** [comment]
I've ran into this issue twice today with more classes. Is there any way to have those styles _not_ apply to stuff in the code snippet?

**Comment by barryofguilder** [comment]
Looks like this is a duplicate of #178.

**Comment by josemarluedke** [comment]
I just encountered the same issue still.

**Comment by rwwagner90** [comment]
Closing this for now. If anyone is still experiencing this issue, please let us know!

**Comment by barryofguilder** [comment]
I'm still seeing some issues of this where some of the ember-cli-addon-docs Tailwind classes are still interfering with my components. This is a slightly different example than my original one above.

My component that I'm rendering with `<DocsDemo />` creates a listbox that uses an unordered list with a bunch of list items. The issue is, there's a `.docs-md li` class that's used to style list items in markdown that is leaking into `<DocsDemo />`. Even if I add a `mb-0` to my `li` element, it still applies the class that the docs define since it's more specific.

<img width="385" alt="Screenshot 2023-05-25 at 4 33 48 PM" src="https://github.com/ember-learn/ember-cli-addon-docs/assets/5649106/0b3fd2d1-be43-4279-a5e5-6bda55067aee">

The only way I'm able to fix this is by doing what I have in my original post above and creating a more specific CSS style to get rid of it.

I think that it would be good to only apply the `.docs-md` styles to the actual markdown and not any content that's in the `<DocsDemo />` component or any other handlebars components.
