### ISSUE TITLE
{{docs-header/link}} doesn't handle params

### ISSUE THREAD

**Issue by Alonski** [ember-learn/ember-cli-addon-docs#398]
This component doesn't handle params or queryParams.
https://github.com/ember-learn/ember-cli-addon-docs/blob/master/addon/components/docs-header/link/component.js#L19

**Comment by rwwagner90** [comment]
@Alonski can you give an example of when you would need params support?

**Comment by Alonski** [comment]
@rwwagner90 So I actually don't remember 😅

Also we've started migrating from addon docs to Storybook 😬
