### ISSUE TITLE
Add support for PlantUML

### ISSUE THREAD

**Issue by gossi** [ember-learn/ember-cli-addon-docs#399]
[PlantUML](http://plantuml.com) is a descriptive language to write UML diagrams and is embedable in markdown.

This would be a super addition to "draw" diagrams "in code" to support explanation of technical documentation.

**Comment by rwwagner90** [comment]
@gossi are you interested in opening a PR for this? I believe it may be out of scope, but if you wanted to implement it, I think it could be useful!

**Comment by rwwagner90** [comment]
I am going to close this as out of scope, but if anyone wants to implement this or something similar, we would gladly accept a PR!
