### ISSUE TITLE
Errors when using `ember-href-to`

### ISSUE THREAD

**Issue by barryofguilder** [ember-learn/ember-cli-addon-docs#400]
My addon uses [ember-href-to](https://github.com/intercom/ember-href-to) for some of my components and I was noticing a bunch of console errors. I've done some digging and this is what I'm seeing.

If I use `ember-href-to` version 1.15.1 (same as `ember-cli-addon-docs`), I don't see any console errors.

If I use `ember-href-to` version 2.0.1, I get the following error in the console: "Uncaught TypeError: Cannot read property 'apply' of undefined".
<img width="634" alt="Screen Shot 2019-08-16 at 8 47 43 AM" src="https://user-images.githubusercontent.com/5649106/63168840-3d74a400-c003-11e9-9181-f8b42dfadd46.png">

If I use `ember-href-to` version 3.1.0, I get the following error in the console: "Uncaught TypeError: params.shift is not a function".
<img width="647" alt="Screen Shot 2019-08-16 at 8 49 27 AM" src="https://user-images.githubusercontent.com/5649106/63168872-59784580-c003-11e9-847e-5081fe3a80a6.png">

**Edit:** I forgot to mention that this error occurs on page load, and even when it's not a page where my addon is using `ember-href-to`.

**Comment by barryofguilder** [comment]
This could be due to the fact that starting with `ember-href-to` version 2.0.0, it uses Ember's internal routing service to generate the URL.

**Comment by rwwagner90** [comment]
This should be fixed, as we no longer use ember-href-to internally.
