### ISSUE TITLE
Addon clobbers tailwind configuration

### ISSUE THREAD

**Issue by alexlafroscia** [ember-learn/ember-cli-addon-docs#406]
My addon is using `ember-cli-postcss` to manually configure Tailwind as a PostCSS plugin.

The configuration of that instance of Tailwind seems to be clobbering the Tailwind configuration provided by `ember-cli-addon-docs`. For example, I do not want my Tailwind configuration to include the CSS reset; if I configure the `corePlugins` to remove the `preflight` plugin, the `ember-cli-addon-docs` side does not render correctly as it _also_ has the reset removed.

Is there some way to allow the `ember-cli-addon-docs` styles not to be affected by the instance of `tailwind` that is being run on my own CSS?

**Comment by alexlafroscia** [comment]
I’m guessing the reason is

- `addon-docs` adds a Tailwind plugin
- Addon adds it’s own Tailwind plugin
- PostCSS does not allow multiple versions of a plugin and inadvertently replaces the first with the second

I’ve looked around online and haven’t had luck finding information on how to tell PostCSS to run both. I went into the debugger and overrode the `postcssName` (or something) of one of the plugins but that didn’t fix the issue.

**Comment by rwwagner90** [comment]
@alexlafroscia I think we need to do some work to use tailwind manually here, rather than ember-cli-tailwind, as per the discussion here https://github.com/embermap/ember-cli-tailwind/issues/143

I am not sure if that helps or not, but would be a step in the right direction.

**Comment by alexlafroscia** [comment]
Would making that change be enough to get this working?

I'm happy to take a pass at dropping `ember-cli-tailwind` in this add-on if it can resolve my issue, as it's a bit of a blocker for us right now.

**Comment by rwwagner90** [comment]
@alexlafroscia I am not sure if that would fix it, but I suspect it would be helpful. If you have the time to give it a try, that would be great!

**Comment by alexlafroscia** [comment]
@rwwagner90 you confirmed that this isn't an issue anymore?

**Comment by rwwagner90** [comment]
@alexlafroscia I did not, I thought I saw you commented somewhere that it was fixed?

**Comment by alexlafroscia** [comment]
I believe it's fixed!

**Comment by rwwagner90** [comment]
Closing for now, if anyone sees this again, please let us know!
