### ISSUE TITLE
Tests fail in FastBoot when addon uses addon docs + ember-cli-fastboot-testing

### ISSUE THREAD

**Issue by scalvert** [ember-learn/ember-cli-addon-docs#417]
This issue was recently introduced here:

https://github.com/ember-learn/ember-cli-addon-docs/blob/master/addon/initializers/route-anchor-jump.js#L9

In FastBoot, there is no `window.location`, so this line causes tests that are written in an addon that uses `ember-cli-addon-docs` and has tests that `ember-cli-fastboot-testing` to fail.

```
Error while processing route: content-paint location is not defined ReferenceError: location is not defined
    at Class.afterModel (/tmp/broccoli-7127ipwpCiFn887X/out-481-srihash_assets/assets/addon-tree-output/ember-cli-addon-docs/initializers/route-anchor-jump.js:15:1)
```

One solution I can think of is to just not run this reopen if using FastBoot, since it's related to interactive behavior.

**Comment by scalvert** [comment]
👍

**Comment by scalvert** [comment]
Any chance we can get a release out? This is blocking some other PRs of mine due to floating dependency tests.

**Comment by rwwagner90** [comment]
@scalvert I do not have permissions on npm. @samselikoff what's the normal release process? If you would like to give me permissions, I don't mind doing the release.

**Comment by scalvert** [comment]
Ya no worries, @rwwagner90. I figured you may not have release. I can also ping @pzuraq, who's on my team at work.
