### ISSUE TITLE
Add support (or examples) for documenting arguments for glimmer components

### ISSUE THREAD

**Issue by HeroicEric** [ember-learn/ember-cli-addon-docs#424]
Possibly related to https://github.com/ember-decorators/argument/issues/95

The [quickstart in the guide](https://ember-learn.github.io/ember-cli-addon-docs/docs/quickstart) recommends using [ESDoc](https://esdoc.org/) with [`ember-cli-addon-docs-esdoc`](https://github.com/ember-learn/ember-cli-addon-docs-esdoc) if you're defining your components as ES6 classes and even links to [a nice example component](https://ember-learn.github.io/ember-cli-addon-docs/sandbox/api/components/esdoc-component) and [it's source](https://github.com/ember-learn/ember-cli-addon-docs/blob/master/sandbox/app/components/esdoc-component.js). This is great!

I'm currently working on an application that uses a lot of [Glimmer components](https://www.pzuraq.com/coming-soon-in-ember-octane-part-5-glimmer-components/), which are defined as ES6 classes but they're a little bit different than regular Ember components. Since the arguments for Glimmer components are not directly set on the component instance, it seems that we need to provide examples for how a Glimmer component's arguments should be documented, and (I think?) some changes to add support for displaying this information the same way we can with Ember component's arguments.

## Ember component version

```javascript
import Component from '@ember/component';
import { argument } from '@ember-decorators/argument';

export default class PersonComponent extends Component {
  @argument
  firstName;

  @argument
  lastName;

  get fullName() {
    return `${this.firstName} ${this.lastName}`;
  }
}
```

Sample usage of `<Person />` component in a template:

```hbs
<Person @firstName="RWJ" lastName="blue" />
```

## Glimmer component version

```javascript
import Component from '@glimmer/component';

export default class PersonComponent extends Component {
  get fullName() {
    return `${this.args.firstName} ${this.args.lastName}`;
  }
}
```

**Comment by rwwagner90** [comment]
I am not sure if glimmer components are supported in addon docs. @pzuraq do you happen to know?

**Comment by pzuraq** [comment]
The YUIDoc documenter should still work, since it’s comment based. I’m unsure about the ESDoc documenter, it may have a way to do it via comments, which is what I’d recommend for the time being.

**Comment by rwwagner90** [comment]
I think we should likely steer folks in the direction of YUIDoc, since it works with pretty much anything.
