### ISSUE TITLE
Add classes to markdown-transformed tags

### ISSUE THREAD

**Issue by samselikoff** [ember-learn/ember-cli-addon-docs#44]
It's possible to render ember components inside of markdown templates, which is amazing, because it lets you write prose in markdown while still having demos and not having to move everything over to `hbs`.

But, we have a `.docs-md` class that styles tags (`.docs-md h1`, `.docs-md a` and so on), which leaks into component demos.

We need our markdowner to add `.docs-md-h1` class to all h1's it transforms, `.docs-md-p` to all paragraphs and so on. I'm sure it's an option in whatever markdown transformer we're using.

Can someone do this? ❤️

**Comment by dfreeman** [comment]
Marked doesn't seem to support this directly, but it allows you to override a `Renderer` method for each page element (`heading(text, level)`, `link(href, title, text)`, etc.) which would make this possible.

**Comment by samselikoff** [comment]
9468efe7a32a62b3c4a759fb5d93c769927d67b0 closes
