### ISSUE TITLE
Demo not working in markdown file

### ISSUE THREAD

**Issue by ELepolt** [ember-learn/ember-cli-addon-docs#447]
I feel like I'm missing something from the documentation: 

> To show additional functionality, create route-specific components and render them from your template.md files:

So I created a template.hbs file following the same naming convention

`tests/dummy/app/docs/example/demo1/template.hbs`
```
{{! BEGIN-SNIPPET docs-demo-basic-src.hbs }}
{{#docs-demo as |demo|}}
  {{#demo.example name="docs-demo-basic.hbs"}}
    <p>I am a <strong>handlebars</strong> template!</p>
    <p>The value is: {{val}}</p>
    <div>
      {{input value=val class="docs-border"}}
    </div>
  {{/demo.example}}

  {{demo.snippet "docs-demo-basic.hbs"}}
{{/docs-demo}}
{{! END-SNIPPET }}
```

Then using `ember generate docs-page example` I create this:

`tests/dummy/app/docs/example.md`
```
# Example
Example content

{{docs/example/demo1}}
{{docs-snippet name="docs-demo-basic-src.hbs"}}
```

This shows the docs-snippet, but does not actually give the demo.

**Comment by rwwagner90** [comment]
For components, wouldn't  they need to be in a `components` folder? I don't think `tests/dummy/app/docs/example/demo1/template.hbs` is going to work.

**Comment by ELepolt** [comment]
I guess that's kind of my question. So I've now moved `template.hbs` to `tests/dummy/app/templates/docs/components/example/template.hbs`

And `example.md` is now: 
```
{{docs/components/example/demo1}}
{{docs-snippet name="docs-demo-basic-src.hbs"}}
```

But still the same issue.

**Comment by rwwagner90** [comment]
I don't think that directory structure is supported. It's possible something like that is supported with pods, but if you want to create a component and have a directory for all the components for the docs route, I would make a docs folder under components. Try `tests/dummy/app/templates/components/docs/example/template.hbs`

**Comment by ELepolt** [comment]
There it is. Sorry about the confusion, I had cloned this repo and their `demo1/template.hbs` is located at `tests/dummy/app/pods/docs/components/docs-demo/demo1/template.hbs` and I tried to follow the structure a little too strictly. Thanks so much for your patience!

**Comment by rwwagner90** [comment]
Glad you got it figured out @ELepolt!

**Comment by ELepolt** [comment]
I'm sorry, but I've got one more issue :)

From [the same page](https://ember-learn.github.io/ember-cli-addon-docs/docs/components/docs-demo) I'm trying to get the `Press Me` button working, but it's not able to find the component. What is the file structure that I need to support this?

**Comment by rwwagner90** [comment]
@ELepolt I'm not sure I understand. Can you elaborate?

**Comment by ELepolt** [comment]
I'm starting to wonder if some of my issues here are due to the pods structure being used. Every example that this repo uses has the folder as `demo-name/demo#/` then `template.hbs` and `component.js` files.

So the `template.md` for that page simply has `{{docs/components/docs-demo/demo2}}`. The `demo2` folder has both `template.hbs` and `component.js` files, and `component.js` contains this action: 

```
    toggleIsShowing() {
      this.toggleProperty('isShowing');
    }
```

So my folder structure just uses `docs/example/demo1.hbs` and Ember errors that it cannot find an action. My question is what do I need to name the component and where should it be placed to properly call that action?

**Comment by rwwagner90** [comment]
@ELepolt I think this is not an issue with this repo, but an issue with placing Ember components in general. I would look at the Ember guides.
