### ISSUE TITLE
Clarity around automated deployment to gh-pages

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-learn/ember-cli-addon-docs#454]
I've had a couple confusions with the deployment process, and am wondering if others have had the same issue.
 
When I first started the project, I had to manually create the gh-pages branch.. but I also had to make sure it was an empty branch -- delete all my repository files -- as I don't need addon source deploy as if it's a website. There is no home index.html though: https://github.com/NullVoxPopuli/ember-jsqr/tree/gh-pages  I haven't yet dug in to this to see what could be wrong. I suspect it _may_ have something going wrong around this code: https://github.com/ef4/ember-cli-deploy-git/blob/master/index.js#L44 (one of the ember-cli-deploy plugins addon-docs uses)
 
So, idk if other people have had these issues, and additions to the guides would be helpful?
 - create _empty_ gh-pages branch before deploying
 - ?? (whatever I need to do to fix the root index.html (and related assets) missing issue

-----

### Update (maybe not directly related to deployment, but I am using GH Actions with all this)

Forgot that I also had to do this in the GH Action

```
run: echo "::set-env name=ADDON_DOCS_VERSION_PATH::${GITHUB_REF##*/}"
```
related: https://github.com/ember-learn/ember-cli-addon-docs/issues/437

**Comment by rwwagner90** [comment]
The addon docs default is to only publish a version, and not overwrite the root. If you run `ADDON_DOCS_UPDATE_LATEST=true ember deploy production` it should force it to overwrite the root.

**Comment by NullVoxPopuli** [comment]
Ah, _that's_ what that means. Cool. I'll give it a go! Thanks!

**Comment by NullVoxPopuli** [comment]
also, I had to do this:
```
        run: echo "::set-env name=ADDON_DOCS_VERSION_PATH::${GITHUB_REF##*/}"
```
for github actions.
(just documenting stuff for others to find it quicker)

**Comment by rwwagner90** [comment]
Definitely feel free to open a PR to talk about GitHub actions in the official docs 😃

**Comment by NullVoxPopuli** [comment]
Once I figure out a good setup, I def will!

**Comment by NullVoxPopuli** [comment]
Yay, the root of my gh-pages has content now! https://github.com/NullVoxPopuli/ember-jsqr/tree/gh-pages

**Comment by jkeen** [comment]
Also running into trouble with some of this setup. I've got a custom domain for my gh-pages site, and it github wants you to put a `CNAME` file at the root. I tried adding that manually to the gh-pages root (seemed like a good idea at the time) but then every time I deployed that file it would get deleted and would knock the site offline.

Turns out you need to stick that `CNAME` file in `/tests/dummy/public` in your addon as I discovered from deep within the ember discord. Adding this comment for future travelers
