### ISSUE TITLE
ember install ember-cli-addon-docs forces plugin choice without context

### ISSUE THREAD

**Issue by elwayman02** [ember-learn/ember-cli-addon-docs#455]
If someone has come to addon-docs for the first time and is starting to install it, the first thing they'll do is run `ember install ember-cli-addon-docs`. The CLI prompt then asks "Which documentation style would you like to use?" and provides two options: YUIDoc & ESDoc. The user likely has no context as to why they would choose one over the other, and there is no option to opt-out of this choice and install the appropriate plugin separately in the future. Even more confusingly, the official [Quickstart](https://ember-learn.github.io/ember-cli-addon-docs/docs/quickstart) guides make no mention of this prompt and instead recommend installing the plugins separately.

There are a couple of conflated issues here:

1) There is no context for how to choose between the two options presented.
2) If you don't know how to choose, there is no option to defer that choice and install the plugins separately.
3) The Quickstart guides are written in a way that implies there IS a way to defer that choice and expects you to install them separately.

**Comment by rwwagner90** [comment]
You can remove the specific npm packages and add the other ones to switch from YUIDoc to ESDoc.

**Comment by elwayman02** [comment]
Yes, you can, but that doesn't really address the concern here, which is that we're forcing the user to make a choice with no information, and that becomes friction for onboarding.
