### ISSUE TITLE
Update examples/boilerplate to Octane

### ISSUE THREAD

**Issue by elwayman02** [ember-learn/ember-cli-addon-docs#460]

**Comment by jrock2004** [comment]
I would be willing to help with this if this is something we would want to do? Would we have to keep both examples or just use octane syntax?

**Comment by rwwagner90** [comment]
@jrock2004 sorry for the late reply! Would love some help with this. I think we should update everything to only modern / Octane syntax. No need to keep both Octane and classic around.

**Comment by RobbieTheWagner** [comment]
I think this is done now? Going to close, but if anyone notices something that needs updating, please feel free to open a PR!
