### ISSUE TITLE
there is a mismatch in generation of docs json

### ISSUE THREAD

**Issue by gokatz** [ember-learn/ember-cli-addon-docs#465]
Thanks for this beautiful package which helps all the ember addon to maintain classy docs ❤️ 

In my case, the name in the `package.json` and in `index.js` file are different. 
* My `package.json` has a scoped name (`@org/pkg`) as I have to publish this addon with the namespace.
* `index.js` file is having just `pkg` as I have to use just `pkg` whenever I refer this addon.

However, the `ec-addon-docs` generate the link using the name from `package.json` while the output folder has the file path obtained from `index.js`

So, from my example, 
* generated link will be like http://localhost:4200/docs/@org/pkg.json
* generate file output path will be like `dist/docs/pkg.json`

Ideally, we should have used either of the names in both places! Thanks for any help.

**Comment by rwwagner90** [comment]
ember-cli does not support setting different names in package.json and index.js I don't think. I would recommend syncing those names up if you can.

**Comment by gokatz** [comment]
I should! but I cannot do that atm :(
Also, I'm using Ember CLI 3.12 and it works fine for me when I have different names. Won't it be much easier if we fetch names from a single source?

**Comment by rwwagner90** [comment]
@gokatz ember-cli has not supported naming them differently for at least a year or two. I know I encountered many issues when I had a project where the names didn't match, and you should be seeing a deprecation warning in your console saying ember-cli doesn't support it right?

**Comment by gokatz** [comment]
Yeah, you are right. I can see the code for this in ECLI source. Even I expected after your first comment. Somehow, there was no warning in my console. 🤔 

I can understand the necessity and will see if I can use same name in my case.

**Comment by rwwagner90** [comment]
Since ember-cli does not support the mismatch, I am going to close this. Hope you are able to get your names the same!
