### ISSUE TITLE
Maintainer / Alternative

### ISSUE THREAD

**Issue by gabrielcsapo** [ember-learn/ember-cli-addon-docs#468]
We just converted to use `ember-cli-addon-docs` for the [Ember Engines Docs](http://www.ember-engines.com). As `ember-cli-addon-docs` are no longer being maintained is there a migration plan to something else? 

I find it incredibly useful that the community can use one type of method for creating fully-featured docs sites with ease. No longer maintaining and improving `ember-cli-addon-docs` seems like a loss for our community.

**Comment by rwwagner90** [comment]
@gabrielcsapo this is maintained and I've been doing my best to keep it up to date.

**Comment by gabrielcsapo** [comment]
I was deriving that from the readme it says:

```
AddonDocs is still actively being used by many addons, but is effectively in maintenance mode as the original authors are no longer working on this project.
```

So new features and closing issues are a part of the maintenance mode?

**Comment by gabrielcsapo** [comment]
I only ask as I am interested in contributing some fixes as ember-cli-addon-docs has been incredibly useful for improving the ember engines doc experience

**Comment by rwwagner90** [comment]
@gabrielcsapo yes, everything is part of maintenance mode, it's simply a warning that those who created the addon are no longer involved. I use this for all my addons, and plan to help keep it running as long as I can!
