### ISSUE TITLE
Markdown is not working properly 

### ISSUE THREAD

**Issue by villander** [ember-learn/ember-cli-addon-docs#471]
I have a big issue in ember-engines site, markdown is working fine on GitHub repo - https://github.com/ember-engines/ember-engines.com/blob/master/tests/dummy/app/templates/docs/bundling.md

but it doesn't work on-site or local - https://ember-engines.com/docs/bundling

reproduction is available on the master branch - https://github.com/ember-engines/ember-engines.com

ember-engines/ember-engines.com/issues/95

**Comment by rwwagner90** [comment]
@villander what's not working about it?

**Comment by villander** [comment]
@rwwagner90 the **bullets** is not working 

In Ember project 

![image](https://user-images.githubusercontent.com/10222774/80920307-4ea64200-8d45-11ea-8c9d-bc2d852014ec.png)

In GitHub 

![image](https://user-images.githubusercontent.com/10222774/80920315-58c84080-8d45-11ea-888b-ab37f3e576ab.png)

**Comment by villander** [comment]
We fixed adding some workaround - ember-engines/ember-engines.com/pull/97

**Comment by rwwagner90** [comment]
@villander thanks for the info, I believe this should fix it https://github.com/ember-learn/ember-cli-addon-docs/pull/472 it will add the tailwind list style classes by default after that is merged.

**Comment by villander** [comment]
thanks a lot @rwwagner90, looking forward to seeing it released
