### ISSUE TITLE
addon-docs fails with latest ember-cli-babel

### ISSUE THREAD

**Issue by elwayman02** [ember-learn/ember-cli-addon-docs#476]
Addon-docs fails to build if you upgrade ember-cli-babel to 7.22.x, due to a failure in ember-cli-clipboard.

It's possible that upgrading to the latest ember-cli-clipboard (0.15.0, currently on 0.13.0) will fix this issue.

**Comment by rwwagner90** [comment]
@elwayman02 I opened a PR to update ember-cli-clipboard https://github.com/ember-learn/ember-cli-addon-docs/pull/496

Will merge and get a new version out soon, and hopefully it'll fix things!

**Comment by rwwagner90** [comment]
@elwayman02 I released 0.9.0, which seems to work with latest ember-cli-babel, I think. Can you confirm this is fixed?

**Comment by elwayman02** [comment]
It appears to work locally, reproducing in CI now to confirm: https://github.com/elwayman02/ember-scroll-modifiers/pull/149
