### ISSUE TITLE
Remove version/sha postfix from Class URLs

### ISSUE THREAD

**Issue by samselikoff** [ember-learn/ember-cli-addon-docs#48]
e.g. 

```
http://localhost:4200/docs/api/DocsHero-0.1.0+daa3b6a3
```

should just be

```
http://localhost:4200/docs/api/DocsHero
```

**Comment by pzuraq** [comment]
This ties in with the work I'm doing on the API Docs plugin system, since that's all about revamping the data model

**Comment by pzuraq** [comment]
URL and ID structure have been revamped in #58, going to close this
