### ISSUE TITLE
loadSearchIndex throws error in fastboot

### ISSUE THREAD

**Issue by ryanto** [ember-learn/ember-cli-addon-docs#50]
```
App is being served by FastBoot
There was an error running your app in fastboot. More info about the error:
 TypeError: Cannot read property 'get' of undefined
    at Class.loadSearchIndex (ember-cli-addon-docs/services/docs-search.js:320:1)
```

https://github.com/ember-learn/ember-cli-addon-docs/blob/master/addon/services/docs-search.js#L77

https://github.com/ember-learn/ember-cli-addon-docs/blob/master/addon/components/docs-viewer/x-search/component.js#L24

What do you think of moving this to `didInsertElement`? I can PR it if it's the right approach.

**Comment by dfreeman** [comment]
Fixed by #51. Thanks @ryanto!
