### ISSUE TITLE
Out of the box GitHub Actions support

### ISSUE THREAD

**Issue by buschtoens** [ember-learn/ember-cli-addon-docs#525]
It would be great to get out of the box support for GitHub Actions or at least a go-to guide.

**Comment by rwwagner90** [comment]
@buschtoens I would be glad to work with you on this. We have a lot we need to do to modernize this project. I've been slowly chipping away at it.

**Comment by buschtoens** [comment]
I got it working in https://github.com/ember-intl/ember-intl/pull/1425, without the use of `ember-cli-deploy-git-ci`, thanks to the help of @dfreeman.

I was trying to base my setup on @NullVoxPopuli's setup in [`ember-jsqr`](https://github.com/NullVoxPopuli/ember-jsqr/blob/master/.github/workflows/docs-for-release.yml), where he _is_ using `ember-cli-deploy-git-ci` with a `DEPLOY_KEY` env, but couldn't get it to work for the life of me. Turns out the `DEPLOY_KEY` secret I had set on GitHub was missing the final `\n`, which caused `ssh-add` to fail.

Anyhow, the `DEPLOY_KEY`-less solution is superior anyway IMO.

The only annoying thing is that the credentials are set via `git config --local`, so they aren't available in the repo that is cloned by `ember-cli-deploy-git`. I had to manually steal them, which is definitely not very pretty.

Unless a really nice `ember-cli-deploy` pattern / plugin for GitHub Actions emerges, I'm inclined to say that we should ditch it in favor of a GitHub Action (for deploying to GitHub pages that is).

**Comment by rwwagner90** [comment]
It would be nice if we had a CI agnostic solution, so things could be built and deployed on Travis, GitHub Actions, Circle etc. but if it is easier to just support GitHub Actions, I do think that is the best choice to lock down on.

**Comment by buschtoens** [comment]
Definitely, CI-agnostic would be best - I agree. We don't necessarily need to _drop_ `ember-cli-deploy` in order to adopt GitHub Actions. We could maintain support for both, but it would mean double work.

Ideally we'd have a nice GitHub Actions plugin for `ember-cli-deploy`, but I doubt that's easily possible.

**Comment by NullVoxPopuli** [comment]
👋 just wanted to say that I've been updating ember-jsqr a bit, and the GH Workflow I had for addon-docs didn't work anymore (used old / no-longer-existing / insecure GH Action API). I removed that bit and now only docs updates on the master branch are deploying. I'm investigating a bit still

**Comment by NullVoxPopuli** [comment]
Turns out I had a `[skip ci]`-type behavior on my deploy of tags. oops. https://github.com/NullVoxPopuli/ember-jsqr/commit/7812771e1be02f288e32e1ae39020ef07c65af4f

**Comment by NullVoxPopuli** [comment]
nope, that wasn't it. It seems my tagged workflow isn't triggering at all 🤔

**Comment by RobbieTheWagner** [comment]
I have documented the GitHub Actions setup here https://ember-learn.github.io/ember-cli-addon-docs/docs/deploying
