### ISSUE TITLE
List our supported Ember version(s)

### ISSUE THREAD

**Issue by billy-addepar** [ember-learn/ember-cli-addon-docs#53]
Does `ember-cli-addon-docs` support Ember 1.11 and 1.13? I am trying to use this addon for my open source and I got the error:

```
Using a version of ember-cli-shims prior to 0.1.0 will cause errors while loading Ember Data 2.3.0-
beta.3+. Please update ember-cli-shims from 0.0.6 to 0.1.0.
An error occurred in the constructor for ember-data at 
/home/travis/build/Addepar/ember-table/node_modules/ember-cli-addon-docs/node_modules/ember-data

An error occurred in the constructor for ember-cli-addon-docs at 
/home/travis/build/Addepar/ember-table/node_modules/ember-cli-addon-docs
```

**Comment by pzuraq** [comment]
`ember-cli-addon-docs` won't be able to support any version prior to Ember 2.3 due to its usage of contextual components. I think there's other ways we can solve this issue.

**Comment by samselikoff** [comment]
anything to do here atm? Or should we close for now

**Comment by pzuraq** [comment]
I think we should state somewhere what minimum version of Ember we support so we know that going forward

**Comment by samselikoff** [comment]
@pzuraq Is this still true? I'll add it to the docs.

AddonDocs only supports _addons_ on 2.3 or higher? Or addons who's devDependency of ember-cli/ember is 2.3 or higher? We should make sure to use clear language here and I'm a bit confused

**Comment by pzuraq** [comment]
Addon docs can support addons whose dev dependency of Ember is 2.3+. 

If we can make it so that docs apps and dummy apps are separate by default, addons can have any support matrix they want, they just won’t be able to run docs apps through ember-try on older versions of Ember. `ember-decorators` and `ember-table` don’t have any acceptance style tests, which is how we test older versions of Ember with them.

**Comment by samselikoff** [comment]
So if you write an acceptance test against your docs site, you can't run it against older versions of Ember via ember-try? I think we do this in Storefront though?

**Comment by pzuraq** [comment]
It looks like you go back to Ember 2.8, which we definitely would support based on features we use. I’m talking like Ember 1.13, before contextual components existed

**Comment by samselikoff** [comment]
Ahh 2.3 der. Sorry I was thinking 2.13 for some reason.

**Comment by pzuraq** [comment]
I think 2.8+ is a good range to support, or 2.12+
