### ISSUE TITLE
Fails in Ember Canary

### ISSUE THREAD

**Issue by elwayman02** [ember-learn/ember-cli-addon-docs#666]
My addon has started failing builds because of errors with ec-addon-docs in Ember Canary:

```
- originalErrorMessage: {{component}} requires a component definition or identifier as its first positional parameter, did not receive any parameters.: (error occurred in 'ember-cli-addon-docs/components/api/x-component/template.hbs'
```

More info: https://github.com/elwayman02/ember-user-activity/runs/1510950766

**Comment by rwwagner90** [comment]
@elwayman02 yeah, our own build here is failing too. I haven't had time to look into why yet.
