### ISSUE TITLE
Update `demoURL` on installation

### ISSUE THREAD

**Issue by dfreeman** [ember-learn/ember-cli-addon-docs#68]
Ember Observer looks for a `demoURL` key under `ember-addon` in an addon's `package.json` to optionally add a link to that addon's demo/docs site. We could set this for the host in our default blueprint if there isn't one already present.

**Comment by kategengler** [comment]
I think using the "homepage" field in package.json should also be considered. It is used by the `npm docs` command to open a doc site. For example, if set on ember-try `npm docs ember-try` would open the correct website.

**Comment by spencer516** [comment]
@kategengler — anything I can do to help getting Ember Observer support for the `homepage` property? I'm happy to put together a PR — but it's not clear where the Ember Observer API code is...?

(I've just updated the PR to add this functionality and use `homepage`: https://github.com/ember-learn/ember-cli-addon-docs/pull/114 ).

**Comment by dfreeman** [comment]
Thanks @spencer516!
