### ISSUE TITLE
API reference rendering bug

### ISSUE THREAD

**Issue by samselikoff** [ember-learn/ember-cli-addon-docs#7]
If you visit /docs/api you'll see I have some of the text form the components. Right now the data is rendered using double curlies. When I try to render as HTML using triple curlies `{{{ }}}`, the rendering isn't cleaned up as I navigate around the app.

After we figure this out I can go back to designing out these pages a bit more and making some useful components for people to use.

**Comment by locks** [comment]
Ember bugs:
- https://github.com/emberjs/ember.js/issues/14978
- https://github.com/emberjs/ember.js/issues/14924

**Comment by samselikoff** [comment]
For some reason I was unable to reproduce with same dependencies in an app without the API doc json generator, maybe someone else can give it a try

**Comment by dfreeman** [comment]
It looks like the bug doesn't strike with double curlies and `htmlSafe` strings, so we could just work around this for now by rendering an HTML-safe version of the description string (or even something gnarly like an `html` transform for that model attr, as a super quick fix)

**Comment by samselikoff** [comment]
@dfreeman nice work!
