### ISSUE TITLE
Limit the number of matches we show per search result

### ISSUE THREAD

**Issue by dfreeman** [ember-learn/ember-cli-addon-docs#70]
This is particularly painful with short search terms, but it could easily happen with longer ones if they appear a lot in a single document.

![search](https://user-images.githubusercontent.com/108688/37005943-f26ec530-20a3-11e8-8e49-1b6caa3199c9.gif)

**Comment by samselikoff** [comment]
lol.

i will fix this

**Comment by samselikoff** [comment]
https://github.com/ember-learn/ember-cli-addon-docs/pull/122 closes
