### ISSUE TITLE
Addon Doc's own homepage has broken styling

### ISSUE THREAD

**Issue by ef4** [ember-learn/ember-cli-addon-docs#746]
Links are currently unreadable because they're the same color as their background:

<img width="676" alt="Screen Shot 2021-02-11 at 11 09 56 AM" src="https://user-images.githubusercontent.com/319282/107663732-b33de800-6c59-11eb-861d-6451e46c09aa.png">

**Comment by rwwagner90** [comment]
@ef4 this has been an issue for awhile. It's due to the CSS variables and trying to have a theme color. We should probably just remove that and instead ship a white background.

**Comment by rwwagner90** [comment]
It was a quick fix to remove the brand color from the body background. I think that's the main issue here.
