### ISSUE TITLE
`setupRouter` deprecation warning 

### ISSUE THREAD

**Issue by Windvis** [ember-learn/ember-cli-addon-docs#766]
The browser console shows the following warning on the latest version:

`DEPRECATION: The use of Ember.Router in setupRouter is deprecated. Please use the router service. [deprecation id: ember-app-scheduler.setupRouter]`

Updating to ember-router-scroll v4 [should fix that](https://github.com/DockYard/ember-router-scroll/blob/master/CHANGELOG.md#400).

**Comment by rwwagner90** [comment]
@Windvis would you be interested in submitting a PR with the fix? I think it's not as simple as changing the dependency version.

**Comment by Windvis** [comment]
Yea, it seems the router no longer needs to be extended. So in theory the [AddonDocsRouter](https://github.com/ember-learn/ember-cli-addon-docs/blob/a3e3a35dba83f6d9357c854164ecf1c785383712/addon/router.js#L22) is no longer needed either.

Should I show a warning message that extending `AddonDocsRouter` is no longer needed? Or should it be kept in case it's needed in the future?

**Comment by rwwagner90** [comment]
I think we may still need `AddonDocsRouter`. It just would not need to extend `EmberRouterScroll` anymore potentially.
