### ISSUE TITLE
Quickstart install issue

### ISSUE THREAD

**Issue by cmackenz** [ember-learn/ember-cli-addon-docs#78]
`ember install ember-learn/ember-cli-addon-docs`                                                                                                                               

```
Yarn: Installed ember-learn/ember-cli-addon-docs
WARNING: Could not figure out blueprint name from: "ember-learn/ember-cli-addon-docs". Please install the addon blueprint via "ember generate <addon-name>" if necessary.
Installed addon package.
```

`ember s`

```
WARNING: ember-cli-addon-docs needs plugins to generate API documentation. You can install the default with `ember install ember-cli-addon-docs-yuidoc`
Livereload server on http://localhost:7020
Build Error (Babel)

dummy/components/esdoc-component.js: Unexpected token (28:2)

  26 |     The count
  27 |   */
> 28 |   @argument
     |   ^
  29 |   @type('number')
  30 |   count = 0;
  31 |


Stack Trace and Error Report: /var/folders/d2/_qddrkd50vn4wx7vvfxhhtvc0000gn/T/error.dump.57f8d857050249531c059798577b0bb7.log
cleaning up...
````

```
ember-cli: 2.16.2
node: 6.11.4
os: darwin x64
```

**Comment by samselikoff** [comment]
Did the generator run? Try `ember g ember-cli-addon-docs`

**Comment by alexlafroscia** [comment]
I'm seeing this too.

Originally I followed the instructions on the [usage docs](https://ember-learn.github.io/ember-cli-addon-docs/latest/docs/usage) which say to run

```
ember install ember-cli-addon-docs
```

but the `app/templates` directory of the dependency end up empty, do you can't actually render a `docs` page because those templates are missing.

Then I tried out installation command from the [quickstart guide](https://ember-learn.github.io/ember-cli-addon-docs/latest/docs/quickstart) which says to install from Github instead, like this:

```
ember install ember-learn/ember-cli-addon-docs
```

and then I get this same error.

**Comment by gossi** [comment]
I did `ember install ember-cli-addon-docs`, which will stop right before finish (A manual `yarn add ember-cli-addon-docs` didn't finish either). Here are my logs for trying to install this:

```
ERROR Summary:
  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Command failed: yarn add --dev ember-cli-addon-docs --non-interactive
warning ember-cli-addon-docs > liquid-tether > ember-cli-babel > broccoli-babel-transpiler > babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning ember-cli-addon-docs > yuidocjs > yui > request > node-uuid@1.4.8: Use uuid module instead
warning ember-cli-addon-docs > ember-code-snippet > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
yarn add v1.5.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Command failed: yarn add --dev ember-cli-addon-docs --non-interactive
warning ember-cli-addon-docs > liquid-tether > ember-cli-babel > broccoli-babel-transpiler > babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning ember-cli-addon-docs > yuidocjs > yui > request > node-uuid@1.4.8: Use uuid module instead
warning ember-cli-addon-docs > ember-code-snippet > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
yarn add v1.5.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Command failed: yarn add --dev ember-cli-addon-docs --non-interactive
warning ember-cli-addon-docs > liquid-tether > ember-cli-babel > broccoli-babel-transpiler > babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning ember-cli-addon-docs > yuidocjs > yui > request > node-uuid@1.4.8: Use uuid module instead
warning ember-cli-addon-docs > ember-code-snippet > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
yarn add v1.5.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
    at Promise.all.then.arr (/path/to/my-addon/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

**Comment by cmackenz** [comment]
@alexlafroscia I got it working but I put it together kind of kind of hack and slash.

* I installed via `$ ember install ember-learn/ember-cli-addon-docs`
* then `$ ember install ember-cli-addon-docs`
* then copied their dummy app into mine and modified accordingly
* then ¯\_(ツ)_/¯

Dummy layout :https://github.com/funnelcloudinc/ember-cli-echarts/tree/master/tests/dummy

I don't remember if I modified anything outside of that. I don't believe so.

**Comment by gossi** [comment]
There is a lot confusion between `ember-learn/ember-cli-addon-docs` and `ember-cli-addon-docs`.

- The package is named `ember-cli-addon-docs`
- The quickstart says to install `ember-learn/ember-cli-addon-docs` (so do the comments say so in here)
- On npm the package is `ember-cli-addon-docs`
- The blueprint is `ember-cli-addon-docs`

**Comment by alexlafroscia** [comment]
`ember-learn/ember-cli-addon-docs` would install from Github, while `ember-cli-addon-docs` would install from NPM (or yarn). I think that we want to be installing from one of the registries, I'm just not sure why the guide mentions the Github installation.

**Comment by pzuraq** [comment]
I think it’s a typo or leftover from earlier versions of the guides. Will try to get to a fix soon, PRs welcome!

**Comment by alexlafroscia** [comment]
👍 I'll put a PR together that fixes this and another thing that I thought was a bit confusing in the quickstart guide

**Comment by elwayman02** [comment]
I think the real bug here is #86; I was able to solve this issue with `ember install ember-decorators` for now, until it gets fixed.
