### ISSUE TITLE
Missing files when installing from NPM

### ISSUE THREAD

**Issue by alexlafroscia** [ember-learn/ember-cli-addon-docs#79]
If you install the NPM package for `ember-cli-addon-docs@0.2.0` you end up missing a bunch of files that you need for the docs to work correctly.

For example, the contents of the `app` tree are:

```
app
├── templates
└── transitions.js

1 directory, 1 file
```

The [template files for rendering the `docs/api/item` route](https://github.com/ember-learn/ember-cli-addon-docs/tree/c205237d508e13e1df30e7cc0d43194214b48a2d/app/templates/docs/api) are missing.

There's also some missing addon files, for example:

```
addon/routes
└── docs.js

0 directories, 1 file
```

even though [the commit tagged as `v0.2.0` has more than that in the `addon/routes directory`](https://github.com/ember-learn/ember-cli-addon-docs/tree/c205237d508e13e1df30e7cc0d43194214b48a2d/addon/routes).

**Comment by dfreeman** [comment]
It looks like we got bitten by https://github.com/yarnpkg/yarn/issues/4784. Sorry about that! `0.2.2` is published and should have the full package contents now.

**Comment by alexlafroscia** [comment]
Cool! Thanks for the help :D
