### ISSUE TITLE
Add `docs-md` wrapper class to markdown-generated HTML

### ISSUE THREAD

**Issue by samselikoff** [ember-learn/ember-cli-addon-docs#8]
We need to PR `ember-cli-markdown-templates` to give us an option for wrapping Markdownifies template files with a class, otherwise folks won't be able to easily style those pages.

We want to do this so Markdown templates can stay as pure `template.md` files.

https://github.com/ryedeer/ember-cli-markdown-templates/issues/1

**Comment by dfreeman** [comment]
With today's setup, we'll have to recommend to downstream consumers that they install `ember-cli-markdown-templates` and then configure it accordingly.

Given how lightweight the code in that addon is anyway, would we want to consider just owning the Markdown conversion here? If we did, we'd could automatically set up the preprocessor on behalf of the host app, and we'd be able to ensure that `.md` templates are handled exactly the same way as we treat Markdown in doc comments.

Bonus: `marked` (which we use for the doc comments) allows for setting up code highlighting in GFM-style tagged blocks, which Showdown doesn't seem to support.

**Comment by samselikoff** [comment]
Not a bad idea. I'm game. 

Feel free to run with it!
