### ISSUE TITLE
Suggestion: Optionally hide private classes/fields

### ISSUE THREAD

**Issue by alexlafroscia** [ember-learn/ember-cli-addon-docs#80]
I like to be pretty thorough with `JSDoc`, even with internal classes and methods. Right now, anything that has a commented is shown in the docs, whether or not it's actually public. It would be really cool to be able to hide private stuff, or have something in the UI that allows you to optionally view private stuff as well as public.

Right now the solution is to remove the private documentation so that to doesn't leak into the site, but I'd rather not have to do that. That information can be useful to myself later on, when coming back to some work I did a long time ago.

If this is a feature you're interested in, I'd love to help work on the solution!

**Comment by pzuraq** [comment]
Actually working on this right now 😄 going to push it up lter today

**Comment by alexlafroscia** [comment]
Woo, that's awesome! Glad to hear it.
