### ISSUE TITLE
yuidoc seemingly breaks demo app

### ISSUE THREAD

**Issue by elwayman02** [ember-learn/ember-cli-addon-docs#83]
I just wanted to start simple and consume the hero/navbar components in my existing app as I added more functionality from this addon. However, apparently this addon immediately jumps to doing a lot of additional work that causes my dummy app to literally just fail to build once this addon gets installed. How can I avoid this?

Example Error:

```
Build Error (DocsGenerator)

Cannot read property 'methods' of undefined
```

**Comment by samselikoff** [comment]
I believe this should be fixed now that the doc generators have been moved to external plugins.

Closing for now but please ping here if it's still an issue!
