### ISSUE TITLE
Ember 3.27 and/or embroider/test-setup 0.40 breaks ec-addon-docs

### ISSUE THREAD

**Issue by elwayman02** [ember-learn/ember-cli-addon-docs#830]
Two of my projects using ec-addon-docs are failing to render when deployed, with the same error surfacing when upgrading `ember-source` to 3.27 or `embroider/test-setup` to 0.40.

See: https://github.com/emberjs/ember.js/issues/19538 and https://github.com/embroider-build/embroider/issues/805

**Comment by elwayman02** [comment]
Incidentally, my doc sites that don't use ec-addon-docs have not experienced these issues, so something about the way ec-addon-docs is built specifically runs afoul of the bugs introduced in those versions.

**Comment by rwwagner90** [comment]
@elwayman02 I believe that ember-modal-dialog is the source of a lot of our embroider woes.

**Comment by rwwagner90** [comment]
I think things should be working now, but let me know if they are not.
