### ISSUE TITLE
This addon requires ember-decorators?

### ISSUE THREAD

**Issue by elwayman02** [ember-learn/ember-cli-addon-docs#86]
When installing this app but choosing not to use either the yuidoc or esdoc plugins, I still get an error as this addon apparently adds an `esdoc-component.js` to the consuming app, which cannot be parsed by babel without `@ember-decorators`:

```
Build Error (Babel)

dummy/components/esdoc-component.js: Unexpected token (28:2)

  26 |     The count
  27 |   */
> 28 |   @argument
     |   ^
  29 |   @type('number')
  30 |   count = 0;
  31 |


Stack Trace and Error Report: /var/folders/ch/zl0z6ss91tlgt8jkw0kms1wxk3yc3w/T/error.dump.6f467ea407fe206766a0cc449eee3a04.log
```

**Comment by pzuraq** [comment]
esdoc-component should only be in an ignored sandbox addon that shouldn’t end up in the npm package, we should verify that npmignore is working correctly

**Comment by elwayman02** [comment]
Oooh nvm that's probably what the problem is. I was installing a branch directly from github, so it wasn't using the npm package.
