### ISSUE TITLE
Dependency on `ember-cli-clipboard` commit

### ISSUE THREAD

**Issue by ming-codes** [ember-learn/ember-cli-addon-docs#972]
What's needed in this? We are having trouble importing the addon because the dependency on public Github.

**Comment by rwwagner90** [comment]
@ming-codes it was stuff for Ember 4 and/or Embroider, I forget. It looks like they released a new version though, so we should be able to use the published version.

**Comment by rwwagner90** [comment]
We no longer rely on that specific commit.
